### ISSUE TITLE
Free-standing ATX

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1059]
# The Motivation
Free-standing ATX has a slightly different flow

# The Requirement
Despite its name, a free-standing ATX should eventually appear in a block -- the first block it gives eligibility for (which is one epoch after the ATX should have been published/ when the ATX matures).

In the block, the ATX should appear both as associated ATX and in the list of ATXs.

**Comment by antonlerner** [comment]
As mentioned earlier, free standing ATX must be eventually included in the block which references it. Alongside new changes to the way we calculate active set size, which may be simply stating the  Active set size view in the first block created, there is no actual change needed in the way we publish and store ATXs. 

To support free standing ATX we simply must have it in the ATX pool

- [ ] This requires the ability to sync ATX pools from peers to ensure ATX data to be available when a block references it.
- [ ]  Because all ATXs are now stored either in DB or in the mempool, we also must allow a referenced ATX to be retrieved from other nodes when a block is received.

Additional changes will be required when we get the full spec regarding the calculation of the active set size

**Comment by moshababo** [comment]
Obsolete.
