### ISSUE TITLE
Broadcasting gossip messages to all neighbours

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1157]
At the moment, we first broadcast a message (new block, new atx) to ourself, then we validate it, and if it is valid we propagate it.

There is no reason to limit the first broadcast: should be sent to all neighbours.

**Comment by lrettig** [comment]
Is the idea here that a node doesn't need to first validate messages that it generated itself, before broadcasting them?

**Comment by lrettig** [comment]
We discussed this on the dev call today. Per @antonlerner, we do in fact want to validate self-generated messages before gossiping them as a sanity check, since mesh state could have changed since the message was generated in such a way that it's no longer valid. There are other things we can do, however, such as prioritizing outbound messages (see, e.g., #2391).
