### ISSUE TITLE
ATX builder shouldn't store previous atx

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#1204]
Currently, the atx builder stores the most recent atx that was generated in order to use it as the previous atx when coming to generate the next atx. This causes bugs where the atx builder uses the cached atx although (due to other bugs) the atx was never introduced in any block.
This cache is useless since we anyway need to validate that the atx is in the db before using it.

**Comment by barakshani** [comment]
An alternative approach is to update the cache after we broadcasted the ATX, received it, validated it syntactically, and propagated it.

This should be sufficient, since if we think that the ATX is valid, any honest miner will think the same.

If it's eventually not in a block, we will have to address it differently (free-standing etc.)
