### ISSUE TITLE
Broker should not accept registration of very late CPs

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1331]
If a broker receives a registration request for a layer in the past (before our clock) he should return an error and not register the layer.

A bug in late registration request caused a node to start consensus on an old layer.

This solution is probably partial as it is not strict.

**Comment by jonZlotnik** [comment]
The "bug" in late registration is just a queue that isn't processed in time. (I presume this happens only when running hare with small round durations, but no further details were provided in this issue, so I can only speculate)

This is an important thing to track (in logs) when we start testing.

Problem with more details is as follows:
Hare's layer `tickLoop` is the one responsible for checking if the hare window was missed.

https://github.com/spacemeshos/go-spacemesh/blob/bb0057417ae6c0929992ef4403083fb981a84a63/hare/hare.go#L439-L451

**The first problem appears here:**
If it wasn't missed, it schedules the first **goroutine** to call the `onTick` method.
The `onTick` method then calls `Register` on the Hare service's broker to register the layer.
https://github.com/spacemeshos/go-spacemesh/blob/bb0057417ae6c0929992ef4403083fb981a84a63/hare/hare.go#L318
If the onTick goroutine isn't scheduled to run before the next tick we end up with the panic described in #2937.

The broker then proceeds to define an anonymous function which gets added to a queue to be processed by the broker's long-lived `eventLoop` goroutine.
https://github.com/spacemeshos/go-spacemesh/blob/bb0057417ae6c0929992ef4403083fb981a84a63/hare/broker.go#L444

**The second problem appears here:**
The `eventLoop` goroutine is "blocking" in that it only processes one item from the broker's `task` channel or `queueChannel` at a time. So, if the `eventLoop` only gets around to processing a Register task after a ton of messages arrive, then it can end up missing a layer completely.

So really, the bug is most likely due to the design of the broker's "task" and message "queue" processing algorithm.

To fix root of the second problem, either the design of the broker has to change, or the task processing needs to take priority over the message processing. As a quick fix, we could try spinning off a gorountine for every message that needs to be processed by the broker so that the `eventLoop` can get to the `task` channel more quickly instead of waiting for messages to be processed.
