### ISSUE TITLE
ATX creation should wait for positioning ATX

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1375]
### Background
Miners need a positioning ATX in order to publish their ATX. Genesis flow is different for finding positioning ATX and hence miners who join after the genesis may not be able to publish their ATX because they don't have a previous ATX and at the time of the creation attempt they haven't received any ATX from gossip.

### The solution
We should wait for a positioning ATX every time we want to create a new ATX. It can be implemented using a channel in which we can receive pos ATX, similar to subscribing to PoET proofs. Notice that there is an edge case where the epoch changes from the moment we started to create the ATX and waited for pos ATX to the moment we actually received one. In case the epoch changes the channel should bring the relevant pos ATX.

There is a todo in the code regarding this issue:
https://github.com/spacemeshos/go-spacemesh/blob/29c645f095cb28864c1ddc0c90f0bee0b9aece1e/activation/activation.go#L457-L466

@noamnelke - please review description
@zalmen - should we add any tags?

**Comment by noamnelke** [comment]
Made some minor edits. There's one issue I have with your last sentence:
> In case the epoch changes the channel should bring the relevant pos ATX.

I think the calling code (ATX creation) should manage the timeout, cancel the subscription and request an ATX in the next epoch if the time passes, not the pos ATX fetching code as you suggested.

**Comment by noamnelke** [comment]
Also worth noting that we encounter a problem caused by this when configuring short 3 layer epochs. Since ATXs are published during the 3rd layer of each epoch at the moment, new miners who try to create their ATX challenge to send to the PoET do so before existing miners have had a chance to publish their ATXs for the epoch. The new miners then fail and only retry in the next layer == next epoch, never being able to catch up.

**Comment by gavraz** [comment]
> Made some minor edits. There's one issue I have with your last sentence:
> 
> > In case the epoch changes the channel should bring the relevant pos ATX.
> 
> I think the calling code (ATX creation) should manage the timeout, cancel the subscription and request an ATX in the next epoch if the time passes, not the pos ATX fetching code as you suggested.

Yes. Didn't mean to go much into detail. Just noted the general solution and the edge-case.

**Comment by barakshani** [comment]
The source of the problem is that (once failed) miners try to create an ATX only on a layer clock tick.

The description of the issue is that it may never happen that a miner both have:
a. clock tick for a layer in epoch j,
b. positioning atx in epoch j.
So she can never create an atx.

In other words, by that time she has the positioning atx, the next clock tick is for epoch j+1.

(it's not really an issue, since epochs should be long enough so when don't experience this clock race)

**Comment by noamnelke** [comment]
It's still an issue, IMO, if miners wait another layer for no good reason.

I agree that we should broaden the fix a little to not wait for clock ticks at all and just run in a loop and wait for conditions to apply.

**Comment by moshababo** [comment]
@noamnelke still relevant?
