### ISSUE TITLE
Sync slowed down because of TXs

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#1469]
# Overview / Motivation
We added flows to transactions which include saving in a DB. this added processing time for txs which resulted in sync taking too long. (this also affects handling blocks from the gossip network)

# The Task
TODO: Clearly describe the issue requirements here...

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by almogdepaz** [comment]
all processing that does not relate to block data validation should not block the insertion of blocks into the database

**Comment by noamnelke** [comment]
Transaction indexing may have affected performance, but the effect is not as significant as originally thought.

Regarding @almogdepaz's comment - not sure I agree. If the additional time is for DB indexing then performing the two tasks non-atomically will cause issues down the line when the index isn't guaranteed to match the DB contents. If there really is a performance issue there and we can't find a better solution (we're very far from that point) then we can consider separating the two and creating a mechanism for signalling when the DB is/isn't in sync with the index, and possibly blocking while waiting for it to become synced. This would be a very complex solution, IMO, and I think we should avoid it if at all possible.

I prefer the approach of making the indexing fast enough, or even eliminating the need for the index (not far fetched).

@y0sher - the massive performance hit we thought we saw in the sync test was due to creating transactions without signatures in the test and this is fixed now. I'm surprised to hear that it also has a noticeable impact on gossip. I'd love to hear more about it.
