### ISSUE TITLE
Nipst builder can get stuck on waiting for poet proof

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#1550]
# Overview / Motivation
NIPST builder can get stuck on waiting for results from poet for too long. 
we need to think about when we stop waiting for membership proofs and restart the whole process. 

# The Task
implement a timeout on waiting for poet membership proofs .
# Implementation Notes\
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by moshababo** [comment]
In total we have 3 points of failure related to the PoET service:
1. service isn’t available for registration
2. service doesn’t broadcast a valid proof at the expected time period
3. service proof doesn’t include the miner challenge in the membership list

##### Open questions:
* regarding point 2 - how should we define the timeout value? options:
   1. configurable as `duration`
   2. configurable as a function of `n`, with pre-defined set values. 
   3. configurable as a function of `n`, with pre-defined set values, while adding a verification against the PoET service that the open round is expected run for the configured `n` value. 
* fallback behaviour is to wait for the next layer clock tick before attempting to try again. This is obviously a naïve approach, but is it enough for now? Without introducing multiple PoET services support, we're pretty limited on what we can do.

**Comment by moshababo** [comment]
@noamnelke @barakshani @antonlerner

**Comment by barakshani** [comment]
Note that miners are (should) not exposed to `n` as it is only a parameter of the poet.
Nevertheless, the miner can calculate the epoch length, as layer_duration times layers_per_epoch (maybe that's what you meant by `duration`).

For 2:
At the moment, I think the simplest thing is to combine it with https://github.com/spacemeshos/go-spacemesh/issues/1552, so you wait for at most 2 epochs (the epoch you started building the ATX and the following epoch -- note that in practice it would be less than 1 epoch, since even in a normal poet behaviour, the miner has to wait for a full epoch), and if you don't have the poet proof by then, you abort and start building a fresh atx.

In the future, it will be good to start working on a new atx at an earlier stage, say when you are certain that the poet should have finished by, but not abort the old one, just in case the poet proof will arrive. This means that if it arrives, the miner needs to decide what atx to keep and what to abort. 

For 3, we can abort much earlier (today when it happens, we check at the beginning of each layer if we have the proof, only to find out that we are not included there). If it is very easy to fix, then we can do it now. Otherwise, the general abort procedure (https://github.com/spacemeshos/go-spacemesh/issues/1552) is sufficient.

**Comment by barakshani** [comment]
Just read https://github.com/spacemeshos/go-spacemesh/issues/1552. It is a bit too specific, and talks only about broadcasting (in principal, there is nothing wrong with broadcasting a very late atx).

I suggest to make that issue more general, such that it is responsible for terminating the atx builder, for whatever reason may come. This means that our current issue does not explicitly terminate the atx, but provides the initial cause, that another mechanism will process and start termination.

@noamnelke, since we talked about it, please advise.

**Comment by noamnelke** [comment]
So sorry for the late response, this conversation slipped between the cracks for me.

What I've implemented for 2 in #1619 is what @barakshani said - if a node is waiting for a PoET proof, it will timeout when the ATX's target epoch has passed, i.e. when publishing the ATX would no longer be beneficial, since all block opportunities have passed.

1 and 3 will result in an immediate failure of the NIPST builder, causing the ATX builder to fail. The behaviour then is to wait a layer and try again.

The problem with the current implementation is that if 2 or 3 occurred we shouldn't trust this PoET anymore (ideally, publish a fraud proof). If any of these occur we definitely don't want to use the same PoET for our next attempt. The node currently knows only one PoET, so we can't implement it yet, but we'll definitely want to revisit this in the future.
