### ISSUE TITLE
Invalid ATX when restarting a Node

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1593]
When a Node reloaded with existing database (because of persistency), we see that it creates an ATX as if this is its first ATX (a commitment proof is included):
`received syntactically invalid ATX 35db1: prevATX declared, but commitment proof is included`

When the Node restarts, it writes
`found data to recover on disc`.
Then
`Starting PoST initialization	{"node_id": "2e30e", "datadir": "/home/post/data", "space": "1048576", "rewardAddress": "0000000000000000000000000000000000001234"}`
and
`PoST initialization completed	{"node_id": "2e30e", "datadir": "/home/post/data", "space": "1048576", "commitment merkle root": "d3ac061c13a40fc278b822389138ba24b74c5d0ff63184917858bbee33a72b6b"}`
even though there should be a post initialized already (because of persistency).

**Comment by noamnelke** [comment]
Interesting... I'm not sure why this happens with the existing code, but I'm pretty sure #1619 solves it.

Worth testing again after it's merged, and also adding a test for restarting a node which includes an assertion for this.

**Comment by almogdepaz** [comment]
fyi "found data to recover on disc." refers to the mesh. not sure about recovery for the atxdb etc...

**Comment by lrettig** [comment]
@moshababo I see that you're assigned here, is it okay if I work on this?

> When the Node restarts, it writes
> found data to recover on disc.
> Then
> Starting PoST initialization {"node_id": "2e30e", "datadir": "/home/post/data", "space": "1048576", "rewardAddress": "0000000000000000000000000000000000001234"}
> and
> PoST initialization completed {"node_id": "2e30e", "datadir": "/home/post/data", "space": "1048576", "commitment merkle root": "d3ac061c13a40fc278b822389138ba24b74c5d0ff63184917858bbee33a72b6b"}
> even though there should be a post initialized already (because of persistency).

I've confirmed that all of this is expected behavior, although the log output here is a little unclear. As Almog pointed out, the "found data to recover on disc" has nothing to do with PoST. Even though the log says "PoST initialization completed", it's actually not reinitializing PoST, instead it ran the execution phase. I improved the log output a bit: df769ce6896de1c6b0785f14dd2ccd8cc650c335.

> received syntactically invalid ATX 35db1: prevATX declared, but commitment proof is included

I'm attempting to recreate this, and add a test for this. @barakshani any further log output or info you have here that would help recreate this would be very helpful. Thanks!

**Comment by barakshani** [comment]
Is it always the execution phase or can it be init as well? If the former, let's change the log.
Moreover, it is not clear to me why do we run PoST here. This proof would not be used anywhere. Do we verify the proof? What if we fail?

To give some more context, commitment proof is only given in the first ATX. Hence an ATX that includes a previous ATX should not include a commitment proof.

Perhaps there's some flag that tells us if we need a commitment proof or not, and we don't use it here?
Or maybe the "Starting PoST initialization" that we see is exactly this commitment proof?

**Comment by noamnelke** [comment]
I agree that this can be optimized. I’ve noticed this too when working on
this area.

I can look at it on Sunday.

**Comment by lrettig** [comment]
One anomaly I noticed is that `common/types/activation.go` defines two methods for creating an ATX, [`NewActivationTx`](https://github.com/spacemeshos/go-spacemesh/blob/66e9a7ead2d9b2f32e61cda2aad8b4ed5f4aedff/common/types/activation.go#L119) and [`NewActivationTxWithChallenge`](https://github.com/spacemeshos/go-spacemesh/blob/66e9a7ead2d9b2f32e61cda2aad8b4ed5f4aedff/common/types/activation.go#L145). The first one is used only in tests, while the second is [used in production](https://github.com/spacemeshos/go-spacemesh/blob/66e9a7ead2d9b2f32e61cda2aad8b4ed5f4aedff/activation/activation.go#L416). I suspect these two methods should be collapsed into one, so that the tests traverse the same code path used in production here.

**Comment by lrettig** [comment]
@noamnelke thanks for addressing this - with #1693 both now flow through the same code path. Cool.

I think the remaining to do item here is, if possible, to recreate the issue and add a test for it. I'm going to work on this a bit more, but no luck recreating it yet.

**Comment by noamnelke** [comment]
There’s also the efficiency thing—initial PoST commitment being created
unnecessarily on recovery.

Regarding recreating the issue—might be worth trying to recreate using old
code, pre-ATX overhaul. If that’s successful, check same conditions with
new code and if it doesn’t happen anymore we can close the issue.

**Comment by noamnelke** [comment]
I've created #1700

**Comment by barakshani** [comment]
Closing as this seems not to happen anymore. Reopen if this happens again.
