### ISSUE TITLE
Change log level of ATX timing failure

### ISSUE THREAD

**Issue by AmitShaul** [spacemeshos/go-spacemesh#1618]
# Overview / Motivation
log level is "info" where it should be "error"
log msg: "failed to validate 3b0aa prevAtx epoch (0) isn't older than current atx epoch (0)"
seems like it's located under updateAtxDependencies function,
there's a concatenation of an err msg into a log.info

**Comment by noamnelke** [comment]
This is the relevant code:
https://github.com/spacemeshos/go-spacemesh/blob/ed2745fa39153360dc4901346d6825aa02300750/sync/fetch_queue.go#L247-L272

I don't think this should be an `error`, since it's just an invalid message received from a peer, but I do think that it should be a `warning`.

@almogdepaz WDYT?
