### ISSUE TITLE
Add a mechanism that can wait for the go-routines to finish

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#1639]
node.go may contain calls to go-routines.
For example, go checkTimeDrifts is a go-routines that runs in the background and checks the time drifts.
In order to close such go-routines, we use a term channel that the go-routines can listen to and this channel will be closed when we close the node's services.
In case the routines have some clean up to do we might also want to wait in stopServices func until we are sure all those resources are cleaned.
This could be achieved for example with a wait group.

We should think if we need such a mechanism or not. Currently, it is not important so this is left as a low-priority issue.

**Comment by lrettig** [comment]
Not having this is causing some headaches in the API-related tests I'm writing. One of them monitors all logged errors, and without a way to cleanly wait until all services (launched in previous tests) have stopped running, the test keeps getting polluted with errors from previous tests as services shut down asynchronously. I may need to implement this to fix the tests.

It would also help a lot with #2067 (see also the change I made in 9bc6794f29f7bb7d0deab7aae2870af2c11adae1).

**Comment by noamnelke** [comment]
Consider using Tomb for managing goroutine lifecycle: https://pkg.go.dev/gopkg.in/tomb.v2?tab=doc

In a nutshell, it provides a `tomb.Go(f func() error)` method which you call instead of the regular `go` keyword. You can then call `tomb.Kill()` followed by `tomb.Wait()` which returns when all goroutines have returned.

**Comment by lrettig** [comment]
Good to know. I think we pretty clearly want this, but it will require a pretty significant change to how we run services.

**Comment by noamnelke** [comment]
This is a big change, in the sense that each service now needs to receive a context and listen for termination using it instead of the existing mechanisms. Initializing this context and waiting for termination in the shutdown method are trivial. Replacing calls to `go ...` with calls to `tomb.Go()` takes some work but is pretty straightforward.

I think this can be a great task for one of the Go beginners that asked for something to do (with supervision). WDYT @lrettig?

**Comment by noamnelke** [comment]
If we agree to give this to someone from the community, I'll write detailed instructions in a fresh issue (cross referenced with this one) and close this in favour of that (this one says "consider" and we've now considered it).

**Comment by lrettig** [comment]
I hesitate to mark tasks involving concurrency as good first tasks. It's a good second task :)

**Comment by noamnelke** [comment]
I agree with your sentiment, but I think that with detailed instructions and close supervision this task is mostly "wiring". I think it can also be scoped down by applying this to one module at a time.

**Comment by lrettig** [comment]
I like the idea of doing it one module at a time. As we discussed in chat, it would be nice to design a clean interface that each "app module" implements: it can probably be as a simple as Initialize, Start, GracefulStop, and ForceStop, something along those lines. There's a lot more we could do to improve how we manage app services, but I think this would be a great starting point and is still straightforward enough that anyone could work on it.

**Comment by noamnelke** [comment]
I agree with most of what you said, but I disagree about some details. The service interface that makes sense to me is:

```golang
type Service interface {
    Start()
}
```

Most services already implement this interface (there are a couple of cases where `Start()` takes arguments from the configuration or returns an error, but these can easily be refactored away). So we could put all services in a slice and then start them all using a loop.

I'm not 100% sure the separation between initialization and starting services is even justified. It may be simpler to just have the initialization method start each service and saving the extra step - not sure about this one.

Stopping all services will be done by calling `tomb.Kill()` on the root Tomb. This initiates a graceful shutdown. While we currently only ever stop services when the node shuts down, if we ever need to support stopping a single service (or a subset of services), it's possible to create a child-tomb that can be killed without affecting its parent.

I don't understand what `ForceStop` is supposed to do. If the node is force-stopped (when `panic`ing, or due to a sigkill), all goroutines are force-stopped and there's nothing we need to explicitly do to support that.

Initialize can't conform to a unified interface because each module has different dependencies that it needs to receive during initialization. I don't know of any good dependency injection frameworks for Go. If you do, I'd be interested to know, but either way, this sounds like a separate task, which is larger in scope than this one and we should consider it separately (if you want to advocate for it).

**Comment by lrettig** [comment]
The reason I suggested separating `Initialize` and `Start` is because of the way the app is currently launched in `cmd/node/node.go`: first, an initialize method is called, then later a start method is called. There is already some distinction between these in the way the app/node is architected:

https://github.com/spacemeshos/go-spacemesh/blob/1c818789facf0e7219feb7d8d5737ce6b6776835/cmd/node/node.go#L93-L98

I don't have a strong opinion on adding `ForceStop`. It just seems to be a common pattern in go: see for instance the difference between net.http [`Server.Close`](https://golang.org/pkg/net/http/#Server.Close) and [`Server.Shutdown`](https://golang.org/pkg/net/http/#Server.Shutdown). I can't speak for other services, but in the case of the GRPC API services, a "graceful shutdown" would probably finish serving the current request, then exit, something along those lines.

**Comment by lrettig** [comment]
Related: #514

**Comment by shibe-dev** [comment]
I'd love to give this a try. Would it make sense to hop on a call with either/or both of you @noamnelke @lrettig to hash out the details? I'll be happy to accommodate your availabilities

**Comment by lrettig** [comment]
I think @noamnelke and I need to get on the same page with respect to the interface design first - I'll make a note to discuss this with him next week! Let's keep in touch about it @howydev

**Comment by lrettig** [comment]
Hey @howydev, @noamnelke and I had a chance to discuss this today. We both agree that the [Tomb](https://pkg.go.dev/gopkg.in/tomb.v2) framework makes sense here: read [this post](https://blog.labix.org/2011/10/09/death-of-goroutines-under-control) for some background. Personally I still think that a more advanced interface for services including initialize, graceful stop/force stop, etc., would be nice, but it's probably a separate task and it can be done later. Feel free to work on this. Let us know what questions you have.

**Comment by moshababo** [comment]
@lrettig still relevant?

**Comment by lrettig** [comment]
I think this can be combined with #2094
