### ISSUE TITLE
deleting blocks after process atx failed causes race

### ISSUE THREAD

**Issue by almogdepaz** [spacemeshos/go-spacemesh#1647]
# Overview / Motivation 

once a block is in the database it is considered syntactically valid, blocks that are inserted to the db should not be deleted / should be marked syntactically valid/invalid and pruned later

**Comment by noamnelke** [comment]
A little bit of context: the way it's implemented right now is a bad implementation of an atomic operation for adding the block and the ATXs. When ATXs are in the DB, it's assumed that there's also a block that contains them in the DB.

The current implementation adds the ATXs after the block because it's possible to rollback adding the block, while it's impossible to rollback adding the ATXs. If the insertion would happen in the intuitive order (ATXs first and block later) and adding a block would fail, we wouldn't know which ATXs to delete, since some may have been added to the DB due to previous blocks.

Since @almogdepaz says that the current flow can cause an inconsistent state for the tortoise, a solution has to be found and I don't know of a simple solution.

**If we can wait for free-standing ATXs then this will become a non-issue since ATXs will be added to the DB regardless of blocks and an atomic insertion won't be necessary anymore.**

**Comment by almogdepaz** [comment]
@noamnelke the current flow effects the whole system, the node currently depends  on blocks in the db to be syntactically validated before they are written!!!
gossip block validation, hare , tortoise sync and other modules need that property.
it is very important that we don't break such important behaviors so randomly (i found this issue by accident... )

**Comment by antonlerner** [comment]
closed as we support free standing ATXs
