### ISSUE TITLE
Expose Node status in the api

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1662]
# Overview / Motivation
For open testnet 0.1 users, until we support running go-spacemesh via CLI with a CLI wallet, the only way to know about their node runtime status and to manage their node is via the app GUI. 

Therefore we need the API to support basic full node runtime statuses so the App can query the node for its runtime status and present the user with runtime information. 

For some statutes, specific user action is required. In other cases, the user needs to know that the testnet is down and they need to wait until a new app update is available to run again. 

It is important to put the user in control and empower him/her to know what's going on underneath the UI and direct him to proper action in case it is needed. The more information we share about the node status, the better.

# The Task
Add a status checks to the node API. The app client will periodically call this to receive the current node status and will display the status to the user and in some cases prompt him/her to take appropriate action.

## Proposed statuses and status codes

- 0: `Syncing`: The node is syncing. No action needed - user just needs to wait. We need to return with this status the current syncing layer # and the known tip layer # so we can present a progress bat status to the user and he/she will see that the sync is progressing.

- 1:  `Synced`: node is synced top the tip layer and is running. Important to show the user that the node is up-to-date with the network.

- 2: `Can't sync`: the node is running and connected to the p2p gossip network but is unable to sync in the expected sync time. This means that the Testnet is down or a local node bug. In some cases, restarting the node might fix the issue. In some cases, it will not. We'd like to inform the user to try to restart the app and if he gets this status again the we'll inform him/her to wait for a new app update that is required to join the Testnet again (with or w/o a new genesis). When we'll have app update implemented, we'll prompt the user to update the app if restarting it didn't resolve the issue.

- 3:  `Can't connect to the network`:  This happens when the node is non-routable and bootstrap node (or other nodes he already knows about) do not return neighbors to it. The UI will present instructions how to resolve this. e.g. tell the user what he/she needs to do to configure the network. We have a page about this in the guide. This status is needed because we don't support non-routable nodes for 0.1. If we do support non-routable nodes then this status means a network connectivity issue and the user will be promoted to check his/her Internet connection and restart the node via the UI.

Another sub-status of this, say 3.1 -  another process is already listening on the udp and/or tpc port on the local computer. In this case, the p2p system will shut down on node startup and the node will be dysfunctional.

- 4: `Stopped`. One or more of the node's services such as Hare, Sync or Trtl have stopped. The only remedy to this issue is to restart the node process because the node doesn't have any self-healing features yet. The user has a button to restart the node in the GUI and the app has capability to restart the node process when user presses it. We might even consider the App restarting the node automatically in this case. Sub-status should be the reason id. e.g. The node is closed when NTP drift is identified. It is at least good for user error reports and for providing troubleshooting instructions...

# POST Init Status
Clients should be able to query for POST status. This should return:
- 0: The node is not set to smesh.
- 1:  Initializing - return current # labels written out of total # of labels so we can show smesh progress to thhe user.
- 2: complete - POST init is done.

**Comment by avive** [comment]
@noamnelke  - I think it is going to be useful for debugging to also return the latest known mesh state root and its layer 0 so users can report what they got and compare with each other...

**Comment by avive** [comment]
@noamnelke  Please consider #1544

**Comment by avive** [comment]
@noamnelke - maybe you can add here be some basic docs about the new api cps and how to best use them? e.g. tips & tricks so we need to guess less regarding how to best utilize these nice new node superpowers? We also talked about implementing additional statuses in the future. We should write this down so we can quickly pick up on missing ones when needed...

**Comment by avive** [comment]
@noamnelke - please review / complete the blanks:
`NodeStatus.peers` - the number of currently connected peers in the p2p network.
`NodeStatus.minPeers` - ???
`NodeStatus.maxPeers` - ???
`NodeStatus.synced` - true if node is synced with the network. False otherwise.
`NodeStatus.currentLayer` - the most recent layer number (based on net genesis time ???)
`NodeStatus.syncedLayer` - the last layer that the node has synced.
`NodeStatus.verifiedLayer` - ???

**Comment by avive** [comment]
Running against develop after this feature in, response is missing the `peers` field:
```
{
    "minPeers": "8",
    "maxPeers": "108",
    "syncedLayer": "424",
    "currentLayer": "437",
    "verifiedLayer": "420"
}
```

**Comment by avive** [comment]
Peers is omitted from the result when value=0 and same w synced when it is false.

**Comment by avive** [comment]
I'm a bit confused - my brand new install is syncing but the api shows only 6 peers:
{
    "peers": "6",
    "minPeers": "8",
    "maxPeers": "108",
    "syncedLayer": "10",
    "currentLayer": "577",
    "verifiedLayer": "7"
}
I thought that sync is not supposed to start until peers >= minPeers. It seems that it starts if peers > 0. If this is true then what state the node will not reach when peers < minPeers ? @y0sher @noamnelke - can you guys please clarify?

**Comment by noamnelke** [comment]
## Definitions

| Field | Definition |
|---|---|
|`NodeStatus.peers` | The number of currently connected peers in the p2p network.|
|`NodeStatus.minPeers` | The number of peers the node is configured to try to dial out to.|
|`NodeStatus.maxPeers` | The maximum number of allowed peers, after which incoming connections are refused.|
|`NodeStatus.synced` | True if node is synced with the network, false otherwise.|
|`NodeStatus.currentLayer` | The current layer number, based on the time passed since genesis.|
|`NodeStatus.syncedLayer` | The latest layer with blocks in the mesh.|
|`NodeStatus.verifiedLayer` | The latest layer processed by the state transition function.|

## Other Questions & Answers
> Peers is omitted from the result when value=0 and same w synced when it is false.

This is how protobuf works. `0` / `false` are identical to empty values and are filled-in by protobuf when the response is deserialized. This is the same for all of our APIs, since we never manually serialize/deserialize messages.

> I thought that sync is not supposed to start until peers >= minPeers

This is wrong. Once the node has even one peer it will sync and function completely. Since we validate all of the incoming data, there's no risk in syncing with a single peer, other than the risk of omission / censorship.

> It seems that it starts if peers > 0. If this is true then what state the node will not reach when peers < minPeers ?

There's no state the node won't reach, even if it only has a single connected peer. However, this shouldn't happen unless there's a networking problem.

When a node cannot reach its desired number of dialed out peers this is a security concern. It could indicate that the node is being eclipsed. While the node currently doesn't detect this and raise a flag, if you're thinking about how to communicate this condition to the user - it should be presented as a red flag and they should have limited trust in the node in that case.

## Re-opening Issues
If you're experiencing what you believe is a bug or an issue (e.g. value missing in output) you should open a new issue. If it's related to an existing issue and you want to benefit from the existing discussion you should mention the existing issue in the new one (even if the existing issue is closed).

Re-opening an issue indicates that you believe that the closing PR didn't address the issue (e.g. if there's a bug and after the fix has been deployed, the bug is still happening).

Since this is not the case, I'm re-closing the issue.
