### ISSUE TITLE
Unify 2 state tries into one data structure

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#1818]
We should have one state db not two or more. SVM needs smart contracts state db to operate and is using an eth-like trie for that. Currently go-spacemesh is using a different trie for user accounts and coin transactions.

- Blocked by: SVM initial integration into go-spacemesh.
- Explore using the trie created by SVM for smart contract state and if the performance is acceptable then switch to use it for user accounts and remove the geth trie from the codebase.

**Comment by antonlerner** [comment]
Currently, we are using a trie with RLP encoding to store the state for our node, 
As discussed with @YaronWittenstein, there is still no point in changing the internal structure of the state since it makes no difference to the SVM. 
As for integrations, we need to specify and design a plan for integrating the svm into the node and allowing the svm the ability to modify and read from global state.

**Comment by moshababo** [comment]
Obsolete.
