### ISSUE TITLE
redefine "synced" 

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/go-spacemesh#1823]
we should redefine "fully synced" and apply to different modules.
In particular we should allow the block builder to build blocks even if the miner has no blocks from the previous layer

**Comment by rkasterstein** [comment]
@gavraz may needed as well

**Comment by almogdepaz** [comment]
@gavraz talk to me

**Comment by almogdepaz** [comment]
this issue is pretty easy to solve just passing a delta parameter to the IsSynced method changing it from IsSynced() bool to IsSynced(delta) bool (changes to the logic are obvious).
if we want to address the zero block layers issue as part of this epic, then its a whole other story and we should state it in the description.

**Comment by barakshani** [comment]
If we make this issue (it's actually an epic) an (real) epic, then another concern is the general syncing logic, and in particular the process among all peers, such that if one peer has slow bandwidth, then it make us wait on each and every layer.

**Comment by almogdepaz** [comment]
the hash requests to all peers are not a must.
we can  request ids for a layer from one peer and since peer sampling is random we will discover and reconcile differences in the view recursively when we get the blocks from later layers from different peers

**Comment by moshababo** [comment]
Obsolete.
