### ISSUE TITLE
./merkle/pb/*.proto: No such file or directory

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#1942]
## Description

Cannot build go-spacemesh on OS X from a fresh clone of the develop branch

## Steps To Reproduce

```
> git clone git@github.com:spacemeshos/go-spacemesh.git
> make install
> make build
./scripts/genproto.sh
Generating protobuf for ./merkle/pb
./merkle/pb/*.proto: No such file or directory
make: *** [genproto] Error 1
```

## Environment
Please complete the following information:
 - OS: OS X
 - Node Version: commit c2d52d462ceaad0c587a3333c290d1db031d67aa

**Comment by lrettig** [comment]
Looks related: #1917 
e2bf93bc13fbdfe732c4d3cef416feaf1afe9dc7

**Comment by lrettig** [comment]
This is happening because I had an old protobuf file lingering: `merkle/pb/node.pb.go`. I didn't spot it because the `.gitignore` contains the pattern `**/pb/*.pb.go`. Removing it makes the error go away.

Can we somehow change `scripts/genproto.sh` to fix this issue?

**Comment by noamnelke** [comment]
This is actually a known (but undocumented) issue.

> Can we somehow change `scripts/genproto.sh` to fix this issue?

This is what needs to be done, it's just never a priority.

To shed more light: when we remove a package that has `.proto` files in it, the corresponding (locally generated) `.pb.go` files are not removed (as you noticed, they're `.gitignore`d). `scripts/genproto.sh` looks for all `/pb/` folders and when it finds one without a `.proto` file in it, the error you experienced occurs.

I originally wanted to detect and properly handle this situation in `scripts/genproto.sh` (and `scripts/win/genproto.bat`), but we actually phased out our use of protobuf and the package that caused your error is actually the last one other than `api/pb/api.pb` - which is used with the gRPC server and will remain in use. I think what we should do at some point is simplify the `genproto` scripts to only handle that one `.proto` file.

If you feel like taking it on I'll be happy to review it. Otherwise, it'll have to wait for the next time we do a cleanup week...

**Comment by avive** [comment]
I went through the same thing yesterday - had to manually delete my local merkle directory to make it go away.
