### ISSUE TITLE
Two peers try to connect at the same time and both fail

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#195]
In the remote case where two peers try to connect to each other at the same time, if both try to close what seemed to them as the remote connection, we will end up with two closed connections and zero open connections.

Solution -
We must break the symmetry by having an ID per connection (the ID must be visible to both peers, i.e. should be agreed upon when establishing the session) and in case a peer has two connection with the same tuple - the connection with the lower ID will be closed.

**Comment by moshababo** [comment]
Each connection would be an inbound for one node, and an outbound for the other. If the opposite connection is attempting to proceed handshake (`handleNewConnection`), the first connection entry will be found, and latter will be closed. 

I don't see how both connections will be closed respectively. Can you elaborate more on the scenario? Was is reproduced?

**Comment by moshababo** [comment]
Each connection would be an inbound for one node, and an outbound for the other. If the opposite connection is attempting to proceed handshake (handleNewConnection), the first connection entry will be found, and the latter will be closed.

I don't see how both connections will be closed respectively. Can you elaborate more on the scenario? Was is reproduced?

**Comment by moshababo** [comment]
Each connection would be an inbound for one node, and an outbound for the other. If the opposite connection is attempting to proceed handshake (`handleNewConnection`), the first connection entry will be found, and the latter will be closed.

I don't see how both connections will be closed respectively. Can you elaborate more on the scenario? Was is reproduced?

**Comment by y0sher** [comment]
@moshababo , sometimes, `connections` would dial on the same time ( in tests ). this will create a situation where when trying to dial there's no connection, the node will initiate dial, it will receive an incoming connection at the same time and after checking again (`handleNewConnection`) it will find dialed connection there so it will close the new connection. which each of the peers will close the other connection. hence none of them is listening on a valid connection.

this was fixed in #199
