### ISSUE TITLE
Messages are decrypted in different order than the order of encryption causing the decryption to fail

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/go-spacemesh#198]
New issue template
-

#### Steps to reproduce the actual behavior

Feature request template
-

**Comment by y0sher** [comment]
## Bug description
Currently we use `AES-CBC` with a symmetric key both peers generate.
because the nature of `CBC` (Cipher Block *Chaining*) means- every message is encrypted with a block from the previous encrypted message as an IV. message encryption in CBC mode can't be parallelized, messages must be encrypted, sent, received and decrypted in an exact order, otherwise the receiver won't be able to decrypt the message properly. 
example:
( `MSG1` -> `MSG2` (Decrypted with "G1") -> `MSG3` (Decrypted with "G2") ). when trying to handle the messages asynchronously we lose their order and fail to decrypt a message with the wrong IV.
