### ISSUE TITLE
Increase network ID range

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2113]
## Description
Right now the `network-id` in the config cannot be larger than 128 since it's stored in `int8`.

We should have a larger range to make it easier to segment into different types of networks, e.g., testnet is `1xx`, devnet `2xx`, local networks `1xxx`, etc.

Also I'm not sure why this is an int rather than uint, since I don't think we ever want it to be negative.

CC @avive @noamnelke @y0sher any thoughts to add here? Any reason not to change this?

## Affected code
https://github.com/spacemeshos/go-spacemesh/blob/b4a7bcdd152d5f4af3da00abbadab2439b9ce90f/cmd/root.go#L81

This issue appears in commit hash: b4a7bcdd152d5f4af3da00abbadab2439b9ce90f

**Comment by noamnelke** [comment]
I don't see a problem with increasing the size of this field.

**You can skip this section all the way to the separator, kept it here for sharing my thought process.**

Trying to think where it needs to be included:
- **P2P handshake** - a few extra bytes won't kill us.
- **The Genesis ATX** - every other ATX references it via the chain of positioning ATXs and every block references it via its ATX.
- **PoET** - PoET proof messages don't reference any previous messages, so we may want to include the net ID in every signed message to prevent mixing proofs between networks. I'm not sure we want this, because I'm not sure mixing PoET proofs between networks is an issue. Even if we do add it to the signed message, there's no need to actually include it in the broadcasted message or store it - because this is a global value that the node knows and can just append to every message before validating its signature.

---

This actually got me thinking that we may want to implicitly include the net ID in every signed message and make appending it part of the signing/validating machinery. This means we can make this field arbitrarily large`*` as it's never included explicitly anywhere.

`*` It has to be stored once in the config and there's some cost to appending many bytes to every message, but an 8-byte `uint64` will have negligible impact. We can even make it a short string without noticeable impact, IMO. Another option is to use the genesis time as a net ID - assuming no two nets will start at the same millisecond and we need to know this value anyway.

**Comment by avive** [comment]
I thought we also talked about adding the network ID to the proof of space data to make sure that post data can't be reused across networks. This is a pretty important consideration. I recall @tal-m asking for this in one of the research-dev call.

**Comment by noamnelke** [comment]
This is true, but again - it's implicit, you just add it to each label message before signing it, but no need to store it anywhere. If a node on a different net ID will try to validate it - it will just fail.

**Comment by lrettig** [comment]
To put things into perspective, here are a couple of (partial) lists of Ethereum networks with their network/chain IDs:

- https://chainid.network/
- https://github.com/ethereum-navigator/atlas

**Comment by lrettig** [comment]
We've already hit this limit in the testnet - the last network was 128, and now we have to reset to a lower number, which may be confusing. We should address this soon. CC @narayanprusty
