### ISSUE TITLE
Cannot try system tests outside bors due to hardcoded docker image names

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2163]
Right now the only way to successfully run the system tests is inside CI using `bors merge`, because the docker images that are used by the tests (go-spacemesh, poet) are hardcoded in several config files. grep for "spacemeshos/go-spacemesh:develop" to find others; here's one example:

https://github.com/spacemeshos/go-spacemesh/blob/bc91d5bf2bb95b742eff53be6281dd63022bd347/tests/k8s/bootstrap-w-conf-ss.yml#L24

The only other option is to manually run `make dockerpush` _and_ change these hardcoded image names to match the current branch name.

It should be possible to run system tests locally, or using `bors try`, without doing this.

Possible mitigation: make the docker image names dynamic and passed in from the command line/env/config file. Then the Makefile can alter it based on the current branch/environment.

**Comment by noamnelke** [comment]
This cannot be correct because bors doesn't run system tests on `develop`. It only runs them in `trying` or `staging`.

I have also successfully run system tests from my machine using e.g. `make dockerpush dockerbuild-test dockerrun-mining`.

What made you think this is a problem?

---

I dug a little and the reason it works is this method, which replaces what's configured:
https://github.com/spacemeshos/go-spacemesh/blob/bc91d5bf2bb95b742eff53be6281dd63022bd347/tests/conftest.py#L77-L89

The `CLIENT_DOCKER_IMAGE` env var is set in the makefile here:
https://github.com/spacemeshos/go-spacemesh/blob/bc91d5bf2bb95b742eff53be6281dd63022bd347/Makefile#L30-L48

Intuitive and maintainable... NOT. However, it works 🤷🏻‍♂️

**Comment by lrettig** [comment]
@noamnelke thanks, this was the information I needed to figure out what was going on here. Some of the configs referred to `clientv2` and some referred to `client_v2`. Fixed in https://github.com/spacemeshos/go-spacemesh/pull/2131/commits/de86b4c23fb094256baa50c3f383b309d2e7ad1b, so this issue will go away when #2131 is merged.

**Comment by lrettig** [comment]
While we're on the subject, I still dislike the fact that I have to run `make dockerpush` before I can successfully run these tests locally - it would be even better if this weren't necessary and it could somehow use the local docker image - but given that these tests run remotely over k8s, I suppose that can't be helped.
