### ISSUE TITLE
Improve transaction processing tests

### ISSUE THREAD

**Issue by avive** [spacemeshos/go-spacemesh#2191]
## Motivation

Several transaction processing tests in `processor_test.go` are implemented by comparing strings of formatted json output of the db dump with an expected json formatted string. This is fragile and should be avoided. A better approach is instead of using processor.Dump() to get a json formatted string and compare it with a hard-coded string is to use processor.RawDump() to get a typed go data collection and compare its members in a type-safe way with expected values.

**Comment by noamnelke** [comment]
Just a note on this - it might be SAFER to compare typed values, but it would be MORE fragile, not less (e.g. if an internal data structuring change causes the types to change while the representation stays the same)...

I don't generally like comparing dumps of any sort. I think that tests should be focused on exactly what's important to test - so for example, compare balance and account counter values, and ignore everything else. This makes the test less susceptible to break due to unrelated changes, but more importantly it helps the next developer that reads the test understand what the intention of the test was.
