### ISSUE TITLE
Fix flaky blocks-add-node and other tests

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#2222]
## Description
Sometimes add_nodes test fails when some node does not create the correct amount of blocks per epoch

this happens here:
https://github.com/spacemeshos/go-spacemesh/runs/1428531039

the error is usually:
```
>           assert blocks_per_layer == wanted_res, ass_err
E           AssertionError: node 3314eab40ebc14bdc912d2b03309b002869308a96a2860757024ee6f35a3d675 failed creating the avg block size
E           blocks created per layer 1.0, wanted average block per node 0.8
```

## Steps To Reproduce
run `make dockertest-blocks-add-node`
or 
`python3 -m pytest -s -v ./tests/sync/test_sync.py --tc-file=./tests/sync/config.yaml --tc-format=yaml` 

## Expected Behavior
all test should pass, a miner should create 1 block per layer in average at least

## how to investigate
we should look at their declared active set and see it matches other miners active set 
we should also at the blockOracle and the blockBuilder to make sure they don’t have any errors and they are active at all times

**Comment by y0sher** [comment]
Some observations:
- The node tried to sync on atxs when P2P wasn't ready hence it assumed no atxs in first epochs
- A mechanism we had when we're not synced was changing our state to be "synced" while we're on gensis to let atxs flow in the gossip this might've made some atxs missing as we joined and opened gossip after they started sending.


( @nkryuchkov  is working on a fix to both of these )

- We saw a non-consistent case where atxs handling flow is stalled for the whole test after handling the first synced atx. we still don't know the root cause, might be because of atx requests intersecting with atx syncing or something else in this flow. this is being under investigation.
