### ISSUE TITLE
Create timed ticker and message exchanger component

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/go-spacemesh#2249]
In order to implement the beacon we must agree on a set of ATXs to calculate the beacon from this set

the proposed solution is 

> The proposed solution for creating a beacon is as follows:
> 
> 1. Create a proposal for a beacon:
>    
>    * take all ATXs received in last epoch (i -1)
>    * concat them into a single proposal message and sign it
>    * Each smesher partitions the valid proposals received in the previous epoch into three sets:
>      
>      * Timely proposals: received up to δ after the end of the previous epoch.
>      * Delayed proposals: received between δ and 2δ after the end of the previous epoch.
>      * Late proposals: more than 2δ after the end of the previous epoch. Note that honest users cannot disagree on timing by more than δ, so if a proposal is timely for any honest user, it cannot be late for any honest user (and vice versa).
>    * A party’s initial input to the consensus algorithm is the set of timely proposals.
> 2. Reach consensus over set of ATXs to construct a beacon from
>    
>    * for K rounds : in each round that lasts δ, wait for proposals to come in
>    * create a voting message that references all seen proposals within δ time frame and send it
>    * for next rounds wait for δ time, and construct a message that points to all messages from previous round received by δ
>    * After K rounds had passed, tally up votes for proposals using simple tortoise vote counting
> 3. Create random beacon coin
>    
>    * for all messages that passed the global voting threshold, take the ATXs they have pointer on
>    * hash all ATX into a single value
>    * Beacon value received
https://github.com/spacemeshos/SMIPS/issues/29

for this solution we need to have a generic protocol ticker capable of sending an inital message and following messages - aslo classifying them into "timely" and "late"

**Comment by nkryuchkov** [comment]
_From https://community.spacemesh.io/t/tortoise-beacon-based-on-bad-vrf/100:_

# High Level Protocol

1. **Proposal Phase:** smeshers submit a “proposal” for randomness to be included in the beacon.
2. **Consensus Phase:** smeshers run a consensus protocol to agree on which proposals are *valid* (i.e., will be included in the beacon).
3. **Output:** the valid proposals are concatenated, and the hash of this string is the beacon value.

# Proposal Phase Implementation

We can use the smesher’s VRF keys to do two things:

* Sample a subset of ATXs whose proposals are eligible. We need very few—only enough to ensure that there is at least one honest proposal included.
* Compute the proposal itself.

## The proposal itself

We can allow *any* arbitrary string (since honest parties will use a random string, and at least one will be included), but for extra security I think it’s better to use the sampling vrf output. (i.e., the proposal string will be x_id.

# Consensus Phase

We talked about two options for the consensus phase: with and without sampling the participants.
Below I describe the version without sampling (i.e., all smeshers will have to “talk” in multiple rounds). The analysis for this version is simpler, and my guess is that it will require far fewer rounds for equal security.

The basic idea is to use the core tortoise protocol, together with a weak coin (the weak coin is generated using the “bad” VRF).

**Initial Input** :

* Each smesher partitions the valid proposals received in the previous epoch into three sets:
  1. *Timely* proposals: received up to δ after the end of the previous epoch.
  2. *Delayed* proposals: received between δ and 2δ after the end of the previous epoch.
  3. *Late* proposals: more than 2δ after the end of the previous epoch.
* Note that honest users cannot disagree on timing by more than δ, so if a proposal is timely for any honest user, it cannot be late for any honest user (and vice versa).
* A party’s initial input to the consensus algorithm is the set of timely proposals.

**Consensus rounds** :
Parties execute the core tortoise algorithm for the set of proposals, treating this set as a “layer” and each proposal as a “block”.

* In the first round, every party sends a vote for all timely proposals (it can send this vote as a single message consisting of all the IDs it wants to vote for). It also includes a list of delayed proposal IDs (it votes against those initially, but might change its vote later). An honest party *always* votes against late proposals.
* In every subsequent round, every party:
  * counts the votes from all previous round for every timely and delayed proposal. Only votes that were received by the end of round i are counted in round i+1. Each vote is weighted according to the weight of the id that sent it.
  * if the sum of votes for a proposal is greater than θL, it votes for it. If the sum is less than −θL, it votes against it. Otherwise, it votes according to the weak coin.
  * Since each party votes for a subset of the identities sent in the first round (parties never vote for late proposals), subsequent round votes can be encoded as a bit-string relative to identities sent in the first round. For our choice of parameters, the probability that more than 100 identities will be chosen is less than 2^-40, so we can assume each vote consists of 100 bits.
