### ISSUE TITLE
Check for updated docker image before running system tests

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2329]
Right now, if I run system tests locally, I have to remember to `make dockerpush` with my latest code changes, or else a.) all of the tests will fail with a very opaque error (if I forget to push any image matching the current branch), or b.) they'll run against an older version of the code. It shouldn't be too hard to add a check that a docker image has been built, and pushed to dockerhub, containing the current code in the branch, every time we try to run system tests. The workflow should be something like:

1. `make dockerbuild` in the current branch
2. Compare the output image hash to the latest image hash with the same tag on dockerhub
3. Print a meaningful error, and do not start system tests, if an image matching this tag and this hash isn't found on dockerhub

This might also prevent issues like the one we ran into today in #2328

**Comment by noamnelke** [comment]
Running `make dockerbuild` is costly, so we don't want to run it on repeated runs (otherwise, making it a step in the testing code is simpler than your solution).

Here's an alternative: We could use tags that are the commit hash instead of the branch name. We could first check if a tag exists and run a build and push only if it doesn't. This doesn't account for cases where we run with uncommitted changes, so we could check if the repo is dirty and if it is - add the timestamp (or some other differentiating value) to the tag name - causing a new build for every run in that case.

**Comment by lrettig** [comment]
I stupidly made this same mistake again. We should address this.

> This doesn't account for cases where we run with uncommitted changes, so we could check if the repo is dirty and if it is - add the timestamp (or some other differentiating value) to the tag name - causing a new build for every run in that case.

I think we already handled this part, by adding `-dirty` to the tag name in this case.
