### ISSUE TITLE
Add exception votes against blocks the base block votes for

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2424]
## Description
In the verifying tortoise, when selecting a base block, a node considers the set of blocks in every layer against the "local opinion" for that layer. It adds exceptions to vote _for_ blocks that are in the local opinion but that the base block doesn't explicitly support, and it adds exceptions to vote _against_ blocks that are in the layer but not in the local opinion (which the base block doesn't already explicitly vote against). However, there's currently a flaw in this logic: if the base block supports a block in a given layer that the node hasn't seen--i.e., it's not in the database for that layer and it's not in the local opinion for the layer--then the node should add an exception vote against that block. There's currently no (efficient) way to do this because the base block's opinion vector is just a single long list of the blockIDs that it supports, not indexed by layer. We probably need a better data structure.

## Affected code

This issue appears in commit hash: 007bdb9629ef16687e206950c0a1565476aef070

Related files (optionally with line numbers): `tortoise/verifying_tortoise.go`

https://github.com/spacemeshos/go-spacemesh/blob/43cfaeec21f889d65e2f3f7a5efcadef4834c434/tortoise/verifying_tortoise.go#L480-L488

**Comment by dshulyak** [comment]
Base block selection doesn't have to be super efficient, e.g. it makes no difference if instead of 50ms it will take 500ms. I suggest we add a benchmark for base block selection and see how it changes if we will do this task with brute-force (e.g. not indexing). 

We do have BlockLayer index that can be used to discard unwanted exceptions, but we will iterate over all of them. Assuming we have exceptions for 2000 layers, with 30 block per layer, that's 60_000 iterations with 1-2 map accesses. It should not viable to do it without index. Most of the time we won't have that many layers, since this window will grow to that size only if verified layer is stuck.

**Comment by dshulyak** [comment]
Block will be never saved to the database unless all of it dependencies are in database (that include ref block, base block, and all exceptions). I think this fact trivializes the problem described in this issue.
