### ISSUE TITLE
Support rich errors with other fields in addition to the error message

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#2456]
## Description
It's often the case that we want to return an error along with some additional fields for logging. There's a short discussion of the problem and potential solution [here](https://github.com/spacemeshos/go-spacemesh/pull/2453#discussion_r650774967).

## Possible solution
```golang
type LoggableError struct {
	error
	fields []LoggableField
}

func NewLoggableError(str String, fields ...LoggableField) *LoggableError {
	return &LoggableError{error: errors.New(str), fields: fields}
}
```

Then, in order for `log.Err(err)` to be able to return multiple fields we can change the `LoggableField` interface like so:
```golang
type LoggableField interface {
	Fields() []Field
}
```

This requires changing all the types that implement the `LoggableField` interface to return a list of fields (which can hold a single field) and parse that list, probably in `unpack()`.

Bonus points if we make it easy to add a prefix to the keys of a list of fields, then we can add an `err.` prefix to all those fields, to essentially namespace the fields and avoid the possibility of collisions.

Another possibility for bonus points is if we extract fields from [wrapped errors](https://blog.golang.org/go1.13-errors), and possible add an `err.` prefix for each nesting level.

**Comment by lrettig** [comment]
This is exactly like what context does, but in reverse. Which feels incorrect to me. Context, such as fields, flowing down from higher layers has meaning at lower layers, but I don't think the reverse is true. The context is gone. That's why error types are so simple, and self-encapsulated. In cases such as this, I think the caller should add the context when it prints the error. If more localized context is needed, a better pattern would be to break the block in question out into its own method (where context is passed as an argument), or alternatively to pass a function _down_ and use that to print the error.

**Comment by lrettig** [comment]
Here's a reasonably elegant pattern that should work for us to pass things like loggable fields back up to a caller in case of error. I'll create a proof of concept:

- https://stackoverflow.com/a/49188589/2397068
- https://www.ribice.ba/context-upstream/

**Comment by lrettig** [comment]
Here's a proof of concept: https://github.com/spacemeshos/go-spacemesh/commit/edd33e074f18a70cf82f7780c877b6e8660582fe

context is powerful, man 🪄

**Comment by noamnelke** [comment]
Your POC doesn't work. Context objects are immutable. Calling `context.WithValue()` results in a new context that you then have to pass back upstream somehow. I actually learned this from the links you sent. They suggest working around this by including a pointer to a mutable object in the context before passing it downstream and then mutating that object. I think this is clunky and, although possible, it seems like a misuse of context.

Another disadvantage of your proposed approach is that it requires changes to the caller that prints the log when you want to add fields to an error in the called code. My solution is to add support to the `log.Err()` method and then any error with an associated field will be properly handled.

**Comment by kgritesh** [comment]
I have recently started exploring spacemesh, and have found it to be quite interesting. I would love to  start contributing and was wondering if i can start working on this issue

**Comment by lrettig** [comment]
Hi @kgritesh , welcome! Feel free to dive in. The best place to start is usually with a proposal that we can review and comment on. This is relatively self-contained and not on an immediate critical path so I think that's fine. @noamnelke feel free to add thoughts.

**Comment by kgritesh** [comment]
Hi @noamnelke @lrettig there are two potential solutions that exist in my opinion.

- Solution proposed by @noamnelke  [above](https://github.com/spacemeshos/go-spacemesh/issues/2456#issue-920347565). The only challenge with this approach is that we have to change the signature of all the Field creator methods(Time, String, Bool, err) to return LoggableField instead of Field as they could potentially wrap multiple fields instead of a single one.  One issue with this approach is that 99% of times we will have LoggableField with only one actual zap.Field, but for that 1% of cases, we have to do the extra work of looping over the array of fields.
  
- Instead of changing LoggableField, we change Field to wrap one or more zap.Fields internally and handle them during unpack. The good thing about this solution is that I won't need to change existing LoggableField Implementations, but change the Field creator methods to use a constructor function instead of typecasting as we are currently doing. Field interface would look like this

```
type Field struct {
 field zap.Field
 prefix *string, 
 nestedFields []*Field
}

``` 
During unpack, we check if `nestedFields` exist and unpack them as well. This gives us a very good abstraction for a loggableError, where `error` object is the top-level field and its supporting fields are nested. 

<hr/>

I like the conceptual clarity of 2nd approach better, though it completely changes the semantic of `log.Field` from what it currently is.

**Comment by kgritesh** [comment]
@noamnelke any suggestion on which approach to use?

**Comment by dshulyak** [comment]
There is a pattern that works better with an interface that zap provides ([example](https://github.com/spacemeshos/go-spacemesh/blob/develop/cmd/node/node.go#L312-L324). All new errors should stick to it.
