### ISSUE TITLE
mining test is flaky on develop

### ISSUE THREAD

**Issue by AmitShaul** [spacemeshos/go-spacemesh#2465]
## Description
mining test fails occasionally on develop

https://github.com/spacemeshos/go-spacemesh/actions/runs/944047863

**Comment by antonlerner** [comment]
I've noticed that there has been an issue with sync and gossip, this caused us to think that blocks that were received by sync are late, thus not appearing in valid votes for next hare iteration
This caused miners no to vote on a certain layers blocks this failing the hare consensus 
I believe it is fixed by #2471
