### ISSUE TITLE
CI: Node client wrapper

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#2501]
# Motivation 

Interactions with the node across our CI and tests are scattered and using different methods and tools instead of a unified method. once we'll have such a central unit for all interactions with a node, we'll be able to to upgrade this for all tests and future tests as well. 
This change can precede #2316 or follow it. it will give us the ability to switch the method of data retrieval from the node easily and not be dependent on one method like today with the logs.  

As part of #2494 we're breaking the CI into smaller modules that can be available across our tools and even individually. 

# Design

- A client that can be created once for each node using the data extracted from the required information stored on k8s metadata.
- Ability to execute code in the container
- Run checks against the node using the API or logging (temporarily and with provided client)
- A multi client abstraction to run something on all or a group of nodes.

Eventually we might host these services along with some other clients as an API exposed to test runners like mentioned in #2494

**Comment by y0sher** [comment]
Note: this will probably be an abstraction over the network client in #2502 at first, but the point is to be able to easily replace the internals .

**Comment by avive** [comment]
Can you please clarify a bit. Specifically, are we talking about this pattern?
- If a test (or any other ci client) needs node data or to send a command to the node then it should use one of the existing api services methods, e.g. NodeService, MeshService, GlobalStateService if such a method exists.
- Otherwise, add api method(s) to the DebugginService (which is designed to CI use only).

I think this is a good design pattern to follow and matches the idea that api services outside of DebuggingService are designed mainly for usage by user-facing clients (e.g. smrepl, smapp, dash, explore). Also curious for @lrettig feedback on this.

**Comment by y0sher** [comment]
@avive , you are talking about #2316. this issue is about structure within the CI while you are referring a broad change across node, api and its clients - this is an ongoing issue and not fully related to this.

this issue is meant to make changes like these easier to do, basically breaking the dependency on a specific way of retrieving information. eventually we'll want it to access the API like you mentioned but also if other methods will be needed to perform some checks we could add it within the Node Client. (for example retrieving cpu/mem from the machine or reading a log line).
