### ISSUE TITLE
MeshDB.writeBlock is not safe in the event of the crash

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2547]
## Description
To provide safety if crash happens write must be atomic. Leveldb guarantee atomicity of the write if write batch is used.
The issue exists because we are writing block first and then updating mapping between layer id and blocks in two different databases. This operation has to happen using single database.

Proposed changes:

- introduce different buckets for blocks, layers, etc using single database. bucket needs to have constant number of bytes (e.g. 2 will be enough, 0x0001 for blocks, 0x0002 for layers)
- each current database should be refactored to work on its own isolated bucket.
- writing a block should write a block the same way it does now, and then create mapping using key 0x00020BLOCK_ID
- query for blocks ids should use range scan 

## Steps To Reproduce
- crash node after write a block, but before updating layers index 

## Expected Behavior
writeBlock must use batch write to guarantee atomicity of the write.

## Environment
any

**Comment by noamnelke** [comment]
Thanks for bringing up this important point!

In the past when I suggested this solution @antonlerner raised the point that we're using separate databases because we want separate caches for each database. Is there a way to achieve this with buckets? I'm not familiar with the concept.

If this can't be achieved with leveldb's built in primitives, perhaps we must resort to having our own caches instead of leveldb's, but this obviously makes this change more complex/expensive.

Just to be clear: I think there's absolutely no choice and we must make this change, even if it's very complex. My point is only that it's not as "low hanging" as it seems.

Would love to hear your thoughts.

**Comment by dshulyak** [comment]
The bucket is just a prefix for a key. I don't know what caches leveldb maintains but I don't expect them to have separate caches based on prefix. I always thought that leveldb actually doesn't maintain internal cache, but relies on os page buffer. Would like to double check it. But besides that, we maintain lru caches for some types anyway, so we can generalize it. 

I noticed that there are other places where this pattern is used, I think this absolutely needs to be refactored before mainnet. It will be a source of problems in which people will have to resync the mesh. Maybe we should plan to address it systematically in the future sprints?  (cc @antonlerner)

**Comment by antonlerner** [comment]
blocks were designed to be written bottom up - in a way that interrupting the write should not affect node behaviour. we first write the block itself and then update the block in the layer, if the first fails than there is no actual corruption because we don't have any dangling pointers 
Later we update layer hash - this may be not up to date but I'm not sure it can corrupt database
That being said, although we might lose internal levelDB cache management I think we can definitely merge databases, but this needs to be well designed - as we see there are at least 3 types of data affected by new blocks (block, layer, layerhash)

**Comment by dshulyak** [comment]
If we fail after the block is written, but before the block in the layer is updated - then we a have corrupted state (I don't mean actual physical corruption on disk, but a violation of consistency). The next query for LayerBlockIds will not return the block that was written, but GetBlock will.

**Comment by antonlerner** [comment]
we access blockIDs only from layer prespective, simply storing a block in the DB won't affect the layer, layer hash and eventually state. node will sync on the block again when booting back up so that state will be consistent with others

**Comment by dshulyak** [comment]
Are you sure that it will sync? In the code AddBlock will fail if the block exists in blocks database, even if the block id is not added to the layers database. I can't find other places where block id can be added to the list.

**Comment by moshababo** [comment]
@dshulyak close to be followed by https://github.com/spacemeshos/go-spacemesh/issues/2918?

**Comment by dshulyak** [comment]
Yes this is one of the issues that will be closed by implementing recommendations from https://github.com/spacemeshos/go-spacemesh/issues/2918
