### ISSUE TITLE
Fix vector and threshold arithmetic in verifying tortoise

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2629]
## Description

Verifying tortoise and self-healing currently use floating-point math to determine whether net votes (for/against a block) cross a threshold:

https://github.com/spacemeshos/go-spacemesh/blob/4c7a6da8ed4ef10c3f2ec4cb48802f0be26eadcb/tortoise/util.go#L75-L95

Refactor this to remove the floating-point math.

In addition, the vector type (same file) stores votes as uint64, because it's downstream of block weights (which are uint64). This makes arithmetic, such as calculating net votes, unsafe and requires extra checks:

https://github.com/spacemeshos/go-spacemesh/blob/4c7a6da8ed4ef10c3f2ec4cb48802f0be26eadcb/tortoise/util.go#L44-L52

We should probably just store votes using uint32 instead (and perform the safety/overflow check once, on instantiation instead).

Thank you to @noamnelke for raising these issues in this review: https://github.com/spacemeshos/go-spacemesh/pull/2400#pullrequestreview-719642912.

## Affected code
- tortoise/verifying_tortoise.go
- tortoise/util.go

This issue appears in commit hash: df7c1c1f34deafc6d107f8c167fb204c11ffae7c

**Comment by noamnelke** [comment]
After giving it more thought, I'm not sure that `uint32` will be enough for the weight - we want to maximize the supported range there since we can't predict or cap the maximal total weight in an epoch. So I think that using `uint64` is better.

I've also made a mistake in my review comment - `int64` doesn't have the same positive range as `uint32`, it has a much larger range. The sign bit halves the positive range, but a `uint64` has double the *bits* vs. `uint32`, not double the range!
```
int32              -2,147,483,648 to              2,147,483,647
uint32                          0 to              4,294,967,295
int64  -9,223,372,036,854,775,808 to  9,223,372,036,854,775,807
uint64                          0 to 18,446,744,073,709,551,615
```

I still think the best solution is to separate the sign bit and keep using `uint64`, but if this complicates other code, then maybe keeping the current implementation (`int64` with overflow check) is not too bad.

**Comment by dshulyak** [comment]
Can someone explain what is the problem with float64/float32 ? I am not very familiar with this topic and would like to know more.
I assumed that this is because it is not deterministic (depends on the environment somehow), but after some googling it seems that it is deterministic - https://stackoverflow.com/questions/42181795/is-ieee-754-2008-deterministic.

**Comment by nkryuchkov** [comment]
@dshulyak 

Different results usually happen when using x87 floating-point computation in comparison to SSE2/NEON/soft-float, because x87 uses 80-bit FPU registers, so the precision is different. x87 is outdated and isn't supported since Go 1.16 (https://golang.org/doc/go1.16#386).

When not using x87, the results are the same in most of the cases, however, there're some differences in the implementations that don't guarantee that all computations are the same. As far as I know, the inverse square root operation is designed to return an approximate result and can be implemented differently in different architectures. Also, calculations with and without using FMA instructions can give different results. And we can't be sure that the compiler doesn't use those instructions because it can do optimizations.

Moreover, [the Go spec](https://golang.org/ref/spec#Conversions) says that floating-point numbers can differ on different architectures:

1. > An implementation may combine multiple floating-point operations into a single fused operation, possibly across statements, and produce a result that differs from the value obtained by executing and rounding the instructions individually. 
An explicit floating-point type conversion rounds to the precision of the target type, preventing fusion that would discard that rounding.
For instance, some architectures provide a "fused multiply and add" (FMA) instruction that computes x\*y + z without rounding the intermediate result x\*y. These examples show when a Go implementation can use that instruction:

2. > In all non-constant conversions involving floating-point or complex values, if the result type cannot represent the value the conversion succeeds but the result value is implementation-dependent.

In general, I think that if we would use floats, we would get the same results, but there's no such guarantee and in theory different results are possible.
