### ISSUE TITLE
Fetcher producing many spurious warnings in devnet

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2630]
## Description
We're seeing millions of warnings like the following in the [logs for devnet20](http://34.134.71.78:5601/goto/2e7edb08f2c9c285c0eb4dcdba98d051):

> miner-1 | WARN | fetcher | IVDB hash cf6aa8628b was not found in response from peer GrU6SQjTWty4pybKw1MivCbVsYwG9otsPS5HeQFBsUT6
> miner-38 | WARN | fetcher | IVDB hash cf6aa8628b was not found in response from peer ExREbXHwNFkqUZCUqSwR6kGy1tQNiKiKmMS7oSMAr6aC
> miner-1 | WARN | fetcher | remote peer requested non existing hash 0xcf6aa8628b90392f59f63eb43da25413f7e9434493fe35453570874c67b68b6e leveldb: not found
> miner-1 | WARN | fetcher | remote peer requested non existing hash 0xcf6aa8628b90392f59f63eb43da25413f7e9434493fe35453570874c67b68b6e leveldb: not found

Apptests are producing the same: see, e.g., https://github.com/spacemeshos/go-spacemesh/runs/3231702994?check_suite_focus=true

## Steps To Reproduce
Run app tests

## Expected Behavior
We should not be seeing so many warnings

## Environment
Please complete the following information:
 - OS: Linux
 - Node Version: devnet/20, fd806c7f918481a7fa603f5ec8d6adebaee902c9

**Comment by countvonzero** [comment]
preliminary report on the tons of fetcher log "remote peer requested non existing hash XXX"
- the non-existing hashes was for IVDB (input vector)
- it got reported 2000 times because MaxRetriesForRequest is set to 2000 (set due to this issue)
- it's missing because when syncer syncs a layer, it also try to sync input vector for that layer. but input vector only got saved after hare terminates for that layer. so if syncer tries to sync current layer, this will definitely be missing from peers

potential fixes:
- https://github.com/spacemeshos/go-spacemesh/pull/2612 should stop syncer from requesting input vector from peers for current layer
- TODO: restore  MaxRetriesForRequest to 20. the value was temporarily increased due this issue)
- TODO: only asks for input vector when peer didn't respond in the layer blocks query
