### ISSUE TITLE
Only critical logs should use ERROR logging level

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#2633]
## Description

Currently, some logged errors are actually not errors, but debugging messages and warnings. Therefore, there're too many errors in Kibana which makes finding real issues more difficult. Also, it's not clear what cases need to be investigated and what don't. 

We should use the ERROR logging level only for critical errors which require immediate investigation and which mean that something went wrong. Other logs should be classified as WARN/INFO/DEBUG.

After only critical errors are classified to the ERROR level, we may consider using notifications for such logs.

**Comment by noamnelke** [comment]
Thanks for bringing this up, @nkryuchkov!! I've been having thoughts about this for ages.

I think we should formalize a "logging methodology" that will make logs more consistent and our lives easier.

My thoughts about the matter:
---

As you said `ERROR`s should be reserved for rare and unexpected situations that could indicate a code problem. If an error occurs often, not due to a bug, it means we need to handle this case better. As I see it, errors should only be caused by internal conditions to the node. A database inconsistency is a classic example. 

Any unexpected input to the node should only ever result in a `WARNING`. Messages that fail syntactic validation are a classic example and so is dropping a non-responsive peer.

I still haven't decided how we should handle consensus-related log messages. E.g. a Hare iteration not reaching consensus would cause another iteration to start - I intuitively want to make it a warning.

The difference between `INFO` and `DEBUG` is more about frequency. The default for messages about natural progression of the protocol and node should be info, with frequent "spammy" messages downgraded to debug.

I really wish that as a user I could be able to see a log of only high level info messages and warnings/errors. So for example, I'd like to see a message when the Hare reaches consensus and a layer is validated (every 5 minutes), but every received block (~50 within a few seconds, every 5 minutes) would be spammy. I'd like to know when I publish an ATX (every 2 weeks), but not when every ATX is received (possibly thousands every 2 weeks). I'm not sure if this should be our INFO level, or if there should be another "INFO+" level, or some other mechanism for this (some way of filtering log messages).
