### ISSUE TITLE
Prevent base block conflicts after rescoring local opinion using vote counting

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2678]
## Description
Related: #2402

If a node does not have an opinion on a layer that's sufficiently old, tortoise will calculate its opinion by counting votes (i.e., the global opinion). If the global opinion isn't distinct, it will fall back on the tortoise weak coin. This is a core element of self-healing.

When this happens, it's likely that many otherwise-good blocks won't be marked good because they'll contain exceptions that disagree with the (new) local opinion on blocks that have been rescored in this fashion. We may need to change the way we pick base blocks in this scenario.

## Affected code
https://github.com/spacemeshos/go-spacemesh/blob/9d3a379994e3652eb0378d2cc555588bba91005e/tortoise/verifying_tortoise.go#L1049-L1060

This issue appears in commit hash: 9d3a379994e3652eb0378d2cc555588bba91005e

**Comment by dshulyak** [comment]
I don't understand what this issue is about. It is natural that if we learned new information (new atxs for example) our opinion on certain blocks will change. If we created some block with a base block that was previously good but now it is bad - we can do nothing about it, but this is also should not be an issue.

Newly selected base blocks should be selected based on the best information available, e.g. we definitely should not select something based on old information.
