### ISSUE TITLE
Flaky TestKadDHT_BootstrapSingleBoot

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2700]
## Description

```
    logger.go:130: 2021-08-20T05:02:45.345Z	INFO	dht0         	Stopping bootstrap after 10 tries, address book already contains 8 peers
    discovery_test.go:214: discovery 0 (BcP4r7CYgX58gdnD1sRdCzdR1cR38equuBAa2qHyekdE) has 7 peers min is 8
```

https://github.com/spacemeshos/go-spacemesh/runs/3378775457

**Comment by countvonzero** [comment]
this test fails when it stopped trying after max retries.
https://github.com/spacemeshos/go-spacemesh/commit/670594a32b469d1329638ec4cb90101722bdc0ab

in this scenario, despite having enough peers, 
https://github.com/spacemeshos/go-spacemesh/blob/520d8b9d0c1836fb2663094b3382e90bf4f2d5c1/p2p/discovery/refresher.go#L80
will remove the bootnode from the address book. by the time the test checks, it's 1 less peer than expected.

@y0sher do you think we can keep the bootnode if it didn't achieve the new peer goal after max retries?

**Comment by y0sher** [comment]
Removing the bootnode from the list is there in order to not overload the bootnode, prevent many nodes from trying to create a protocol (tcp) connection with it. we can and probably do already block it from the boot node side (limiting incoming connections). we should probably just not count bootnodes when checking the size of the address book,
