### ISSUE TITLE
Account Balance: proper types to fit all possible amounts

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/go-spacemesh#2718]
@lrettig @avive
I want to ensure that the huge coin amounts can fit in the `uint64` type, that is used now to represent the account `Balance` type.
To answer this main question, I think we have to answer these questions:
- What is the limit for the total amount of coins?
- If there is no limit, what is the inflation plan, when the emission of coins become such small, that it almost can not meet the maximum value of the type?

So, if the total amount of coins is very much more than `18,446,744,073,709,551,615 Smidge` (`18446744.073709551615 SMH`). I can assume, that someday there might appear a rich guy (especially if the market cost of such amount of Smesh will not strive for infinity), that owns such amount or more and he still should be able to receive payments.

If there exists at least a smallest possibility that it is really possible, I think that we have to use a different type to store `Balance` (`*big.Int`) and, as a consequence, we should change `Amount` type in `types.proto` to something more spacious than just `uint64`.

P.S.
Balance type now: https://github.com/spacemeshos/go-spacemesh/blob/746c085fbf1a85c0226d5e82212a1113efb60320/common/types/account_state.go
Pay attention to the comment "TODO" in the file above. It was a BigInt some time ago: https://github.com/spacemeshos/go-spacemesh/issues/2192

**Comment by avive** [comment]
@noamnelke

**Comment by lrettig** [comment]
The planned supply cap will be around 2.4bn SMH. That's a couple of orders
of magnitude greater than the figure you cited, so yes, it seems like we do
need to use a big int.

>

**Comment by dshulyak** [comment]
We should use https://github.com/holiman/uint256 then. I know there was some overhead in go-etheereum since big.Int uses a lot of dynamic allocations and is inefficient in this way, so they made their own library for uint256 type (unless it was changed lately).

**Comment by brusherru** [comment]
So, we also have to decide how we can pass such amounts via GRPC. Just as a string / as two uint64 / something else.
And then, who will create issues to the relates repos? ;)

**Comment by lrettig** [comment]
We could also just return the numbers from the API as a binary blob, as we already do with addresses

**Comment by brusherru** [comment]
I thought about it a little and came to the opinion, that they should be returned as strings.

Here are the pros:
- the implementation of big numbers on the client-side (Smapp / Smrepl / something else) will not depend on the implementation of big numbers on the "back-end" (is it big-endian, little-endian, what part is an exponent, and so on)
- it is human-readable by default

As a con, I see only one thing: worse optimization.
It includes conversion from/to string and validating that `number >= 0 && number <= uint256.MAX_VALUE`.

**Comment by avive** [comment]
> I thought about it a little and came to the opinion, that they should be returned as strings.
> 
> Here are the pros:
> 
> * the implementation of big numbers on the client-side (Smapp / Smrepl / something else) will not depend on the implementation of big numbers on the "back-end" (is it big-endian, little-endian, what part is an exponent, and so on)
> * it is human-readable by default
> 
> As a con, I see only one thing: worse optimization.
> It includes conversion from/to string and validating that `number >= 0 && number <= uint256.MAX_VALUE`.

I think that we should not use strings to represent amounts. One of the reasons we chose to use grpc over http-json for the api is that grpc supports binary data natively and we should use binary fields for all numerical data in a consistent way. Clients should be able to easily create a big number from an UInt8Array / [u8] data so it is best to use string just for display... The BigInt / BigNumber libs are pretty standard by now across platforms but we don't even need for these libs to be compatible with each other because what we pass over the API is basically binary data that represents a big unsigned int. We just need to agree on the Endians when encoding/decoding to/from big numbers.  Please look at https://docs.ethers.io/v5/api/utils/bignumber/ lib - might be more suitable for amount than the built-in js bignum which I previously recommended. There's some interesting info here: https://docs.ethers.io/v5/api/utils/bignumber/#BigNumber--BigNumber--notes--why-not-bignumber-js-bn-js-bigdecimal-etc

It looks like we are not going to be able to escape dealing with Endians until the singularity will be upon us...

**Comment by brusherru** [comment]
BTW, looks like our website has an outdated plan on economics:
https://spacemesh.io/resources#faq-does-spacemesh-have-a-fixed-token-cap

**Comment by lrettig** [comment]
Yup, thanks for the reminder, we will update this shortly!

**Comment by noamnelke** [comment]
We are going to use `uint64` for amounts.

In order to support this, we're going to reduce the divisibility of each coin from `1e18` to `1e9` (for context, each bitcoin is divisible to `1e8` satoshis).

This means that each SMH will now be worth 1,000,000,000 smidges. We'll have a maximum of 2.4 bn SMH, or  2.4 quintillion (1e18) smidges.

```
Maximum number of smidges: 2,400,000,000,000,000,000
Max uint64:               18,446,744,073,709,551,615
```

This has been discussed with @avive and @lrettig. If we missed anything and there's another issue - let me know.

**Comment by noamnelke** [comment]
Further context:

One smidge will be worth one of today's cents when one SMH is worth $10 million.

In 10 years there will be 6m SMH in existence, so if each is worth $10m then the network is worth $60 trillion. The entire world's narrow money supply is estimated at $35 trillion ([source](https://www.visualcapitalist.com/all-of-the-worlds-money-and-markets-in-one-visualization-2020/)) this includes money in checking accounts, which is rehypothecated.

**Comment by brusherru** [comment]
Seems this issue is not actual anymore and we're using the proper data type.
So I'm closing it. If I miss something — feel free to fix me and reopen the issue ;)
