### ISSUE TITLE
sync: if hare takes longer than a layer to terminate node will go out of sync

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#2872]
## Description

In sync we wait for one additional layer before requesting this layer from peers. If hare takes longer then expected to terminate (or if there are any other performance issues) processed layer won't be updated on time and peer will go out of sync. It appears that we can't go out of sync in such case, since sync status affects every other protocol and the whole network will get stuck and won't be able to recover.

We need a better condition for changing sync status from unsynced to sync, so that it both:
- prevents downloading potentially invalid state
- doesn't prevent network from recovering

## Steps to reproduce
In devnet207 hare for layer 3375 took to long to terminate. 3376 was started at 11:04:50, but hare for 3375 terminated only at 11:06:00.502. Therefore at the time when hare for 3776 was supposed to be started, all nodes went out of sync and didn't participate in hare.

**Comment by countvonzero** [comment]
i would actually approach this from the other direction: we need a better condition for changing sync status from sync to notSynced.

my investigation:
from miner 27's log, hare took a long time to finish layer 3375.
hare:
Oct 13, 2021 @ 16:02:00.000	starting hare consensus with blocks	3375
....
Oct 13, 2021 @ 16:06:03.553	number of consensus processes (after unregister)	3375
syncer:
Oct 13, 2021 @ 16:04:50.207	failed to sync to layer	3375
[taking the node out of sync]
mesh:
Oct 13, 2021 @ 16:06:03.553     processed layer set       3375

syncer took the node out of sync because it failed to sync layer 3375 (while current layer is 3376). the failure is due to peers refusing to serve data for layer 3375 because the processed layer is stuck at 3374.
the fact that syncer took the node out of sync further prevents hare to proceed with layer 3376 and further.

there are two issues to fix:
- race condition between syncer and hare
when hare is already running consensus for a given layer, syncer should not do anything to the node other than syncing data (ATX/blocks/TXs) as best effort
currently syncer interferes in two ways:
  - taking the node out of sync when fetching fails
  - validate a layer that hare will also do when the consensus terminates

- peers checking processed layer to decide whether to return layer data is too coarse
when hare terminates layers out of order, say it completes N+1 and N+2 before N. the processed layer stays at N while the peers actually have data for N+1 and N+2. the mesh keeps N+1 and N+2 in a buffer and waits for N to finish before advancing the processed layer from N-1 to N+2. in this case, peers can actually safely serve N+1 and N+2.

@dshulyak @moshababo

**Comment by dshulyak** [comment]
> race condition between syncer and hare

so what the condition would be for a node to go out of sync? or are you are saying that we don't need this condition? i don't really know, as it seems to me that without mesh state sync we will always have edge cases that are not covered

> peers checking processed layer to decide whether to return layer data is too coarse

why is that a problem? it seems to me like an optimization, but i don't see any problems if data for layers N+1 and N+2 won't be served until N is processed

**Comment by countvonzero** [comment]
> so what the condition would be for a node to go out of sync? or are you are saying that we don't need this condition? i don't really know, as it seems to me that without mesh state sync we will always have edge cases that are not covered

node should get out of sync when 
1. data out of sync: it doesn't receive all gossip
2. state out of sync: it finds that its mesh hash (aggregated layer hash) is wrong

for 1 we don't currently have a good gauge. mesh.LatestLayer() is a hint but not accurate.
i am thinking we may need to change the syncer loop interval from
`(processedLayer, currentLayer)` to 
`(min(currentLayer-X, processedLayer), currentLayer)`  
where X is an arbitrary number of layers we want to check for missing data.

for 2 we don't check right now, but should be done when https://github.com/spacemeshos/SMIPS/issues/51 is done.

> > peers checking processed layer to decide whether to return layer data is too coarse
> 
> why is that a problem? it seems to me like an optimization, but i don't see any problems if data for layers N+1 and N+2 won't be served until N is processed

you are right, it's mostly an optimization and probably only matters to nodes that are not synced yet. it can reduce the errors that network is seeing (peers refusing to serve data for N+1 and N+2 for as long as N is delayed (10 layers / 40 hare rounds max) and shorten the sync time for a late node.

**Comment by countvonzero** [comment]
in any case, this is the proposed short-term solution
- syncer syncs layers from peers when it is in notSynced/gossipSync state
- once in synced state, it continues to sync data from peers, but do not take the node out of synced state UNLESS the latest layer lags behind

in essence, while not synced, the node relies on the syncer to advance the processed/verified layer. once synced, gossip/hare/tortoise take over to advance the processed/verified layer.
