### ISSUE TITLE
devnet: hare terminated with block that is not present in mesh

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#2876]
## Description

(labeling with devnet as @dshulyak said this happens a lot in devnet207. in one incident he traced the origin of the block to an external node)

chain of events:
- node received a block `eee46bee2c` via gossip but failed syntactic validation due to error `failed to fetch ref block ebe041945b e: fetch failed after max retries for request`. the ref block `ebe041945b` was produced by another miner 1 min before this failure.
- 500ms later the above failure the node receive block `ebe041945b` via gossip
- later when hare terminates this layer with output that includes `eee46bee2c`, it then failed with `hare terminated with block that is not present in mesh`

it is curious why, in a managed network supposed with good synchrony, that it takes 1 min to propagate. here is a screenshot of the timestamp when the network receive block `ebe041945b`. assuming there is no network delay (very reasonable for managed nodes in the same cluster), it seems the gossip pipeline is clogged somehow. it takes ~400ms for the next miner to receive the block, and another ~400ms to reach the next set of miners. i don't know how much of a outlier this is. in the mining system test, 3 out of 50 nodes suffered this issue.

![Screenshot from 2021-10-15 12-51-22](https://user-images.githubusercontent.com/30611210/137434287-adddee89-5dfe-4363-a788-d45cafc19b4c.png)
![Screenshot from 2021-10-15 12-51-51](https://user-images.githubusercontent.com/30611210/137434292-e9ff42dd-d26d-4283-9bfb-32507c83f4d4.png)
![Screenshot from 2021-10-15 12-53-21](https://user-images.githubusercontent.com/30611210/137434299-d333d861-ea3a-4f76-b681-968f3daa1016.png)

## Steps to reproduce
1. set MaxRetriesForRequest in fetch.go to 20
2. run `make dockertest-mining namespace=$NAMESPACE dump=True`

**Comment by countvonzero** [comment]
discussion btwn @countvonzero @dshulyak @moshababo @noamnelke 

## problem
some miner produced two blocks in the same layer A (ref block) and B. a node received block B via gossip, but failed to fetch its ref block (block A) via peers (after 100 retries from random peers). this can happen when the peer who gossiped block B to us simply dropped out. the node then considers block B syntactically invalid.

later hare terminated with block B in the output. so when tortoise try to verify the hare output, it failed since it didn't save block B in the mesh. this node's verified layer is then stuck.

## discussion
in the spacemesh protocol, all gossip messages guarantee data availability (one only gossips something one already verified), with the exception of hare messages as they are time-sensitive. this poses a security concern for the protocol. a malicious actor can withhold a block from part of the network and cause the network to stall.

gossip+fetching from peers are not optimized. we can prefer to fetch the data dependency from the source of the gossip message. see https://github.com/spacemeshos/go-spacemesh/issues/2703 and https://github.com/spacemeshos/go-spacemesh/issues/2472

the gossip cache in this case also prevents the node from processing block B again when another gossip message of block B was received.

## solutions discussed:
- simply ask more peers for the missing data
- remove block B from gossip cache so that we can reprocess block B later (but this may create a DoS factor?)
- prefer to fetch reference data from peers that gossip the original message
- combine multiple blocks in the same layer into 1 bigger block. this will alleviate this particular issue but does not solve the general data dependency issue in hare messages.

**Comment by noamnelke** [comment]
> simply ask more peers for the missing data

I would like to clarify: we're talking only about a case where the Hare results reference a block that we are unable to fetch from any of our existing peers. This is a special case, because unlike any other reference to an object, if the Hare results include a block then it's known by >1/2 the network with near certainty. In that case only, we'd replace part of our peer list, trying to fetch the missing block. I think we should replace 50% of our peers with new ones. If after the first replacement the fetch still fails - I'd replace the same peers again (always leaving the original 50% of peers, to prevent attacks that would cause nodes to replace all peers with malicious ones). If after 3 replacements we still can't fetch the missing block - we fail.

> remove block B from gossip cache so that we can reprocess block B later (but this may create a DoS factor?)

When I suggested this I was referring to a very specific case: a peer sends us a message with a dependency, then disconnects and we're unable to fetch the dependency from any of our peers. Then we should allow the same message to be sent to us again. Yes, it's a DoS vector, but not a great one, since I can only inflict the attack on direct neighbors. When we implement requesting dependencies only from the same peer that sent us the dependent message, the DoS vector will be eliminated.

> prefer to fetch reference data from peers that gossip the original message

This is much more efficient than what we do today anyway. It also removes the DoS vector from the previous point.

**Comment by moshababo** [comment]
@countvonzero still relevant?

**Comment by countvonzero** [comment]
it still happens in the form of proposal, now we fail and vote for empty layer. closing
