### ISSUE TITLE
tortoise should use current layer as its `Last` layer

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#2921]
## Description

tortoise now uses the last layer output by hare as its `Last` layer. this is different from the rest of the system that consider the current layer the latest layer. and the following two issues make this notion obsolete.

https://github.com/spacemeshos/go-spacemesh/issues/2919
https://github.com/spacemeshos/go-spacemesh/issues/2920

tortoise should simply uses current layer as its last layer for simplicity and correctness.

**Comment by dshulyak** [comment]
Just adding a note that we shouldn't use layer clock in turtle structure, otherwise, last layer might be changed while we are running same method, also there are several computations that are based on the last layer changes (e.g. update thresholds). Probably the easiest would to spawn a goroutine that will listen to layer clock, once trigger it will obtain tortoise mutex and change the last layer.

**Comment by dshulyak** [comment]
Also realized recently that this issue is very important for voting properly on undecided layers (e.g. within zdist). Currently, we will vote against layers within zdist that weren't submitted yet, which is a mistake obviously.

**Comment by dshulyak** [comment]
> Also realized recently that this issue is very important for voting properly on undecided layers (e.g. within zdist). Currently, we will vote against layers within zdist that weren't submitted yet, which is a mistake obviously.

this was solved by tallying votes before voting.

**Comment by dshulyak** [comment]
this should not be implemented. caller always have to tally votes, before casting votes or fetching results from the tortoise. tally votes accepts last layer as a parameter

**Comment by countvonzero** [comment]
@dshulyak how do you propose to resolve the 2nd part of https://github.com/spacemeshos/go-spacemesh/issues/3003

if tortoise always use the "last layer" given to it, not the actual current layer, that means we can never remove data that's only needed within hdist layers (certificate).
syncer will always have to sync a certificate from genesis.

**Comment by dshulyak** [comment]
downloading certificate is an orthogonal problem. certificate in tortoise is needed for a valid opinion vector for a verifying tortoise. if instead of certificate it can just assume that peer gave an honest opinion - that can be used in place of certificate.

alternatively full tortoise can be used for syncing nodes, and then certificate is irrelevant as well. there is a small problem with that, but right now it is better to use full tortoise for new nodes instead of downloading every certificate.
