### ISSUE TITLE
Missing check for duplicate use of voting eligibility

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#2999]
When processing a ballot or block, we never check that a valid eligibility isn't used more than once.

A malicious smesher could create an unlimited number of blocks/ballots in a layer all using an identical eligibility proof.

When we detect this - the expected behaviour is to blacklist the publishing smesher - a mechanism we don't have yet.

Handling this is covered under https://github.com/spacemeshos/go-spacemesh/issues/2998 (by validating that we have no more than a single ballot from a smesher in a layer and that eligibility proofs are all distinct).

**Comment by dshulyak** [comment]
I also discovered this in https://github.com/spacemeshos/go-spacemesh/issues/844 and after my question on slack.

**Comment by dshulyak** [comment]
copying my message from that issue:

From Tal on slack:

> The translation to our case is if someone publishes two ATXs with the same id and the same epoch, or two ballots with the same ATX in the same slot. This is verifiably malicious behavior, and should cause the ID to be canceled (all of its ballots have weight 0, and the node should vote against any type of reward being given to this ID) .

I don't know if we are going to implement proofs of malicious behaviour for mainnet. But the solution for this particular issue should be:
- if there are two or more ballots using the same atxid and same slot they should not be counted by the tortoise (e.g. as the weight is 0)
- we can verify it when the ballot is received and add an additional bit to the ballot stored on disk
- tortoise should load this bit and act accordingly
- at least two malicious ballots can't be pruned, as then we won't be able to identify that ballots were malicious

**Comment by dshulyak** [comment]
This is actually tricky to get right. Storing ballots with non-unique eligibility is a no-go as it makes network vulnerable to spam, and allows to consume storage space without bound. And the fact that this attack is very cheap makes it important to handle it correctly. But there are several problems:

1. Let's assume that 2 nodes received 2 ballots from the same smesher in the same layer but in a different order. If they will learn too late about the 2nd ballot they may use 1st as a base ballot. This will create issues for the tortoise, as each node won't be able to decode some part of the votes.

A simple solution is to let fetcher do its job, and it will invalidate 1st ballot if 2nd ballot is selected as a base ballot. This still will make some votes useless, as tortoise won't be able to decode votes for blocks before base ballot layer.

A more complex solution is to let every node broadcast 1st ballot that has a conflict, every node will *very likely* receive two malicious ballots before it needs to cast votes.

2. If we will keep one ballot in the state we can't prove anything to the node that doesn't know about any other ballots. This is a common case during sync.

It means that we need to either keep two or none. None is not an option, because new nodes will see identity as non-malicious and count votes from it.
