### ISSUE TITLE
Propagate an error to smapp on clock error

### ISSUE THREAD

**Issue by nkryuchkov** [spacemeshos/go-spacemesh#3024]
## Description

When a clock is out of sync, the node exits with exit code `1` and prints the following message to stdout: `Failed to initialize node.	{"errmsg": "check system clock drift: System clock is -3h0m3.648804859s away from NTP servers, please synchronize your OS time", "name": ""}`. Since the process has exited, the app can’t connect to GRPC API to retrieve such error there (or at least it almost doesn't have time to do that).

Therefore, on a crash, all the app can do is to show that some error has occurred. We need to have a reliable way to deliver what error occurred without making the app do complex log parsing.

@brusherru suggested a solution:
> Here is my vision of the ideal solution:
> 1. Determine in Node specification exit codes for all known errors and implement it. So “consumers” can show up the proper error message as they wish easily, without straight depending on messages from the Node. (E.G. it will be very useful if we will support multiple languages in Smapp)
> 2. To provide some details about the error to consumers, the Node should send it to the `stderr` (since it is the only way to tell something while the process is exiting) in  the JSON with specific shape and extracted details to the separate properties. For this particular case it may look like: `{"message": "System clock is -3h0m3.648804859s away from NTP servers", "solution": "Please synchronize your OS time" "details": {"clock": "-3h0m3.648804859s" }, "name": "NTP_UNSYNC", "exitCode": 31}` . Pay attention that I’ve added `details` property which may contain different set of data (for different errors), and it contains `clock` property, so the consumer doesn’t need to extract such value using RegExp or something similar.
>     - Btw, probably it will be better to use more “computer-friendly” format like timestamp. E.G. `nanos: -10803648804859` , but I’m not sure about it.
>     - Also I’m not sure that the `exitCode` should be here, but probably if some errors can occur sending a bunch of errors to the `stderr` before closing and then it closes with some exitCode — it will be easier to find out which one to show. But, again, I’m not sure about it.
> 3. To make easier for consumers to parse the JSON with error details, we can wrap it in special characters, like `STX` (`\x02`) and `ETX`  (`\x03`). So consumers won’t need to do a tricky parsing, just start reading everything from `\x02` and stop on `\x03` and parse everything that was between as a JSON. However, I’m not sure about this particular special characters, probably will be better to use something else. Research needed.
>
> All these stuff sounds a bit complicated, so probably we should make a temporary solution with just extracting an `errmsg` from `stderr` in case if the process exits with code >0. However, I’m sure that the solution proposed above will work much better 🙂

cc @brusherru @moshababo @avive

**Comment by dshulyak** [comment]
Please note that any solution should be generic enough so that it would makes sense when go-spacemesh is running as a standalone daemon and managed using regular linux tooling. Things like adding tokens (0x02 / 0x03) definitely should not be added.  Moreover smapp should be able to tell that the reason of failure is due to the unexpected panic as well.

Every log line is a valid json if `--test-mode` flag is used (it doesn't make sense to call flag test-mode, but that's different problem). smapp should be able to parse some number of last lines (100) and print one or more errors from log. if you prefer you can use a FATAL level to set a reason explicitly.

**Comment by avive** [comment]
My ask from a product perspective for Smapp is that we'll at least be able to identify the dreaded NTP time drift node crash on startup that is not coming via the grpc error stream as this is one of the most annoying issue in smapp. As little as few seconds drift from NTP time servers will cause this and the users have 0 guidance regarding how to address this issue. And Windows systems tend to drift easily if they were turned off for few days.... Addressing this issue is few clicks btw on windows - just turning off and turning on again the switch to sync w windows time server. This doesn't mean of-course that we shouldn't handle this is a generic way.

**Comment by noamnelke** [comment]
Regarding the ability for clients to get a reason for a crash: I agree with @dshulyak that it's best to have a `FATAL` log level for this with a human readable error message, and ideally also an error code for common errors (like time drift) so that the UI can show more info and possibly even a link to further reading and steps to solve the issue if it repeats.

@avive specifically on the NTP issue - being able to handle time drift isn't so hard - I would even dare to say it's a minor fix. We can implement a `Clock` that returns adjusted time based on the detected time drift. I remember that we had harder clock issues (like western time servers not being reachable from China, or failed queries that return Epoch as the current time) we just have to make sure that adjusting the time doesn't make those other issues even worse.

**Comment by nkryuchkov** [comment]
@brusherru, @dshulyak, and I had a conversation about the issue and decided that these are what needs to be done:
1. Change the destination of all logs from `stdout` to `stderr` and ensure that this action doesn't break anything in the infrastructure. This has low priority and may be done later.
2. Rename the `test-mode` flag that makes logger output all logs as JSON's to something more self-descriptive. We should check that nothing gets broken too. Also low priority.
3. Introduce a new field in `FATAL` logs, the field has a common name and contains an error text code like `ERR_CLOCK_AWAY`. With it, the app knows what error occurred and, for example, shows a possible solution. The error text code can also be used for localization (e.g. in the future we can have a web service that accepts a text code (e.g. `ERR_CLOCK_AWAY`) and a language code (e.g. `en-us`) and returns a text in that language (e.g. `Clock is away from NTP servers`). The field is urgent.
4. Implement arguments for error text codes sent to the app to provide additional context. E.g. we can pass what time node is away from NTP servers for the `ERR_CLOCK_AWAY` error. This is urgent but depends on implementing the error text code.

**Comment by dshulyak** [comment]
> @avive specifically on the NTP issue - being able to handle time drift isn't so hard - I would even dare to say it's a minor fix. We can implement a Clock that returns adjusted time based on the detected time drift. I remember that we had harder clock issues (like western time servers not being reachable from China, or failed queries that return Epoch as the current time) we just have to make sure that adjusting the time doesn't make those other issues even worse.

@noamnelke i think the last time this discussion was raised it was accepted that we won't be making things more complex than necessary. usually, OS time will just work. if it doesn't "just" work user probably messed up something and can do a quick google for their OS on how to fix it. if we will do something fancy on our end instead of googling how to fix it for OS he will have to fix it in our client (e.g. adjust config for example). expected UX was described in https://github.com/spacemeshos/SMIPS/issues/55#issuecomment-889790326

imo doing ntp ourselves is worse. sometimes people care about using secure ntp protocol and they can use encrypted ntp extension (nts) (this is the default on fedora afaik), so whatever we are doing will have to be disabled. as you mentioned, sometimes a list of default servers will not be reachable. sometimes ntp servers might be temporarily unreachable. so i would rather postpone doing anything ntp related until we know that some significant portion of users can't configure it using OS tools.

**Comment by nkryuchkov** [comment]
> Therefore, on a crash, all the app can do is to show that some error has occurred. We need to have a reliable way to deliver what error occurred without making the app do complex log parsing.

This was broken down into the following issues:
- https://github.com/spacemeshos/go-spacemesh/issues/3025
- https://github.com/spacemeshos/go-spacemesh/issues/3026
- https://github.com/spacemeshos/go-spacemesh/issues/3027
- https://github.com/spacemeshos/go-spacemesh/issues/3028

So the scope of this issue is just to pass the clock error to the `smapp` using the solution from https://github.com/spacemeshos/go-spacemesh/issues/3027 and then https://github.com/spacemeshos/go-spacemesh/issues/3028

**Comment by brusherru** [comment]
@nkryuchkov I think that only #3027 and #3028 should be done within PR to this issue.
I think that other stuff is less related to the issue and can introduce some bugs.
So If we really need to make changes to stdout/stderr and argument — I propose to file another issue and solve it within another PR. In that way, it won't block us if we will have any problems with it. Especially since todo#2 requires also changes in the different repo (go-spacecraft).

**Comment by nkryuchkov** [comment]
@brusherru Yes, I fully agree, that's what I meant. I just listed all related issues that we decided to have.

**Comment by nkryuchkov** [comment]
I also forgot this issue: https://github.com/spacemeshos/go-spacemesh/issues/3029
