### ISSUE TITLE
mesh: panic with missing tx's when block applied to the state

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/go-spacemesh#3039]
## Description
Node unexpectedly exited yesterday, while it syncing and smeshing.

## Steps to reproduce
1. Run the Smapp (or probably just run Node is enough)
2. Setup smeshing. I'm not sure that this is a required step to reproduce, but my Node does it when it happened.
3. Wait...

## Actual Behavior
Panic

## Expected Behavior
Everything works fine without any panics :)

## Environment
Please complete the following information:
 - OS: macOS 11.6 (20G165)
 - Node Version: 0.2.10-beta.0
 - Smapp version: 0.2.0-beta.2

## Additional Resources 
Here is a part of the log:
```
2021-12-29T02:15:05.093+0530	INFO	8be19.trtl         	attempting eviction	{"node_id": "8be196e35895af351f21bf950b27d8a45f13d0d17b28c7e01f740de4d50dc392", "module": "trtl", "rerun": true, "last-layer-id": 212, "protocol": "HARE_PROTOCOL_outputloop", "sessionId": "a7994ab7-629e-4f9e-96e8-4aceb61c330c", "effective_genesis": 11, "hdist": 10, "verified": 224, "window_size": 30, "last_evicted": 193, "window_start": 194, "name": "trtl"}
2021-12-29T02:15:05.093+0530	INFO	8be19.trtl         	finished handling incoming layer	{"node_id": "8be196e35895af351f21bf950b27d8a45f13d0d17b28c7e01f740de4d50dc392", "module": "trtl", "protocol": "HARE_PROTOCOL_outputloop", "sessionId": "a7994ab7-629e-4f9e-96e8-4aceb61c330c", "old_pbase": 223, "new_pbase": 224, "incoming_layer": 230, "name": "trtl"}
2021-12-29T02:15:05.093+0530	INFO	8be19.mesh         	tortoise results	{"node_id": "8be196e35895af351f21bf950b27d8a45f13d0d17b28c7e01f740de4d50dc392", "module": "mesh", "protocol": "HARE_PROTOCOL_outputloop", "sessionId": "a7994ab7-629e-4f9e-96e8-4aceb61c330c", "layer_id": 225, "reverted": false, "old_pbase": 223, "new_pbase": 224, "name": "mesh"}
2021-12-29T02:15:05.422+0530	INFO	8be19.trtl         	persist tortoise	{"node_id": "8be196e35895af351f21bf950b27d8a45f13d0d17b28c7e01f740de4d50dc392", "module": "trtl", "protocol": "HARE_PROTOCOL_outputloop", "sessionId": "a7994ab7-629e-4f9e-96e8-4aceb61c330c", "duration": "328.949667ms", "name": "trtl"}
2021-12-29T02:15:05.422+0530	INFO	8be19.mesh         	pushing layers to state	{"node_id": "8be196e35895af351f21bf950b27d8a45f13d0d17b28c7e01f740de4d50dc392", "module": "mesh", "protocol": "HARE_PROTOCOL_outputloop", "sessionId": "a7994ab7-629e-4f9e-96e8-4aceb61c330c", "old_pbase": 223, "new_pbase": 224}
2021-12-29T02:15:05.423+0530	WARN	8be19.meshDb       	could not fetch tx	{"node_id": "8be196e35895af351f21bf950b27d8a45f13d0d17b28c7e01f740de4d50dc392", "module": "meshDb", "tx_id": "91643dce03d0e0f5937ef6d997b45514333ac24f0f119dc9b6edc62e1993f058", "errmsg": "could not find transaction in database 91643dce03d0e0f5937ef6d997b45514333ac24f0f119dc9b6edc62e1993f058 err=get value: leveldb: not found", "name": "meshDb"}
2021-12-29T02:15:05.423+0530	ERROR	8be19.mesh         	Fatal: goroutine panicked. Stacktrace: goroutine 368 [running]:
runtime/debug.Stack(0xc99d110f4fc23a33, 0x58f093192ec6edb6, 0xf5e0d003ce3d6491)
	/Users/runner/hostedtoolcache/go/1.15.13/x64/src/runtime/debug/stack.go:24 +0x9f
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc0001e5e00, 0x4fd6ebd, 0x4, 0x500ecf6, 0x2c, 0xc0025b8a18, 0x2, 0x2)
	/Users/runner/work/go-spacemesh/go-spacemesh/log/zap.go:45 +0x9e
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).getTxs(0xc000408620, 0xc00a320b80, 0x1, 0x1, 0xc0000000e0, 0x1, 0x1, 0xba50354f8b569681)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:727 +0x152
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).extractUniqueOrderedTransactions(0xc000408620, 0xc00d4aef00, 0x49ea48f, 0xc001d7a73e, 0x20)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:698 +0x385
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).applyState(0xc000408620, 0xc00d4aef00)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:502 +0x50
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).updateStateWithLayer(0xc000408620, 0x52af380, 0xc00add3ad0, 0xc00d4aef00)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:632 +0x445
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).pushLayersToState(0xc000408620, 0x52af380, 0xc00add3ad0, 0xe0000000df)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:465 +0x407
github.com/spacemeshos/go-spacemesh/mesh.(*validator).ValidateLayer(0xc008781440, 0x52af380, 0xc00add3ad0, 0xc00fc12640)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:348 +0x889
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).HandleValidatedLayer(0xc000408620, 0x52af380, 0xc00add3ad0, 0xe1, 0x0, 0x0, 0x0)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:587 +0x5b6
github.com/spacemeshos/go-spacemesh/hare.(*Hare).collectOutput(0xc0002d3200, 0x52af380, 0xc00add3ad0, 0x52b0280, 0xc00fc12200, 0x0, 0x0)
	/Users/runner/work/go-spacemesh/go-spacemesh/hare/hare.go:212 +0x2ed
github.com/spacemeshos/go-spacemesh/hare.(*Hare).outputCollectionLoop(0xc0002d3200, 0x52af380, 0xc00b6b06f0)
	/Users/runner/work/go-spacemesh/go-spacemesh/hare/hare.go:404 +0x67b
created by github.com/spacemeshos/go-spacemesh/hare.(*Hare).Start
	/Users/runner/work/go-spacemesh/go-spacemesh/hare/hare.go:468 +0xa25
	{"node_id": "8be196e35895af351f21bf950b27d8a45f13d0d17b28c7e01f740de4d50dc392", "module": "mesh"}
2021-12-29T02:15:05.423+0530	PANIC	8be19.mesh         	could not find transactions map[0x91643dce03d0e0f5937ef6d997b45514333ac24f0f119dc9b6edc62e1993f058:{}] from layer 224	{"node_id": "8be196e35895af351f21bf950b27d8a45f13d0d17b28c7e01f740de4d50dc392", "module": "mesh"}
panic: could not find transactions map[0x91643dce03d0e0f5937ef6d997b45514333ac24f0f119dc9b6edc62e1993f058:{}] from layer 224

goroutine 368 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0060e4c00, 0x0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/go.uber.org/zap@v1.19.0/zapcore/entry.go:232 +0x51f
go.uber.org/zap.(*SugaredLogger).log(0xc0025b88c0, 0x804, 0x500ecf6, 0x2c, 0xc0025b8a18, 0x2, 0x2, 0x0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/go.uber.org/zap@v1.19.0/sugar.go:227 +0x111
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/Users/runner/go/pkg/mod/go.uber.org/zap@v1.19.0/sugar.go:159
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc0001e5e00, 0x4fd6ebd, 0x4, 0x500ecf6, 0x2c, 0xc0025b8a18, 0x2, 0x2)
	/Users/runner/work/go-spacemesh/go-spacemesh/log/zap.go:46 +0x21a
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).getTxs(0xc000408620, 0xc00a320b80, 0x1, 0x1, 0xc0000000e0, 0x1, 0x1, 0xba50354f8b569681)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:727 +0x152
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).extractUniqueOrderedTransactions(0xc000408620, 0xc00d4aef00, 0x49ea48f, 0xc001d7a73e, 0x20)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:698 +0x385
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).applyState(0xc000408620, 0xc00d4aef00)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:502 +0x50
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).updateStateWithLayer(0xc000408620, 0x52af380, 0xc00add3ad0, 0xc00d4aef00)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:632 +0x445
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).pushLayersToState(0xc000408620, 0x52af380, 0xc00add3ad0, 0xe0000000df)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:465 +0x407
github.com/spacemeshos/go-spacemesh/mesh.(*validator).ValidateLayer(0xc008781440, 0x52af380, 0xc00add3ad0, 0xc00fc12640)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:348 +0x889
github.com/spacemeshos/go-spacemesh/mesh.(*Mesh).HandleValidatedLayer(0xc000408620, 0x52af380, 0xc00add3ad0, 0xe1, 0x0, 0x0, 0x0)
	/Users/runner/work/go-spacemesh/go-spacemesh/mesh/mesh.go:587 +0x5b6
github.com/spacemeshos/go-spacemesh/hare.(*Hare).collectOutput(0xc0002d3200, 0x52af380, 0xc00add3ad0, 0x52b0280, 0xc00fc12200, 0x0, 0x0)
	/Users/runner/work/go-spacemesh/go-spacemesh/hare/hare.go:212 +0x2ed
github.com/spacemeshos/go-spacemesh/hare.(*Hare).outputCollectionLoop(0xc0002d3200, 0x52af380, 0xc00b6b06f0)
	/Users/runner/work/go-spacemesh/go-spacemesh/hare/hare.go:404 +0x67b
created by github.com/spacemeshos/go-spacemesh/hare.(*Hare).Start
	/Users/runner/work/go-spacemesh/go-spacemesh/hare/hare.go:468 +0xa25
```
The full log for the Smapp session: [panic-log.txt.zip](https://github.com/spacemeshos/go-spacemesh/files/7788083/panic-log.txt.zip)

**Comment by dshulyak** [comment]
It crashed 27 nodes from the recent testnet.

There are a few problems with tx flow:
- tx fetching is best effort. block is syntactically valid even if some tx's is not found . this is not a problem by itself, but we don't have a component that ensures that the tx data is available when block is applied to the state. hence this panic.
- tx pool has a race condition. if there are two or more concurrent tx's from the same origin node may process them out of order. so if serialized order is 3,1,2 - then the 3 will be dropped and not added to the pool. we can change validation for tx's so that it is executed inline, without dispatching it to multiple workers. need to check best practices

UPD i looked into lotus implementation. and for filecoin they have a MaxNonceGap (which is 4), i suspect that it is meant to prevent this exact problem. It is doesn't solve the problem completely, but i think we can use the same approach.

**Comment by noamnelke** [comment]
I wonder how this issue never popped up until now... Did we make any changes to behavior in that region recently? I suspect it's related to libp2p, since it's very similar to the block dependency problem we had right after switching to it. Don't get me wrong - I'm not saying it's libp2p's _fault_ - it's just doing its job, gossiping messages in parallel as efficiently as possible in no particular order, I just think these problems are surfacing now because the old library happened to maintain order (which cost us in efficiency). I'm glad this is surfacing now, if we switched to libp2p post-genesis these fixes would be a nightmare.

Bottom line, we should fix it the quickest way possible for the short term. In the long term (still pre-genesis) we intend to replace the (temporary) nonce scheme with something that will allow some gaps - but how exactly this will work is still a WIP.

I agree with your analysis, @dshulyak, we should add a data availability check to the block application phase and make it pending on having access to all transactions. There can be a long timeout, so e.g. if we're unable to get referenced transactions for 10 minutes only then we panic. This alone will obviously not fix the issue because of the second problem, but we still need this check (and a longer timeout).

Fixing the issue of dropping skipped transactions is harder and also temporary (as I said, we have a long term fix in mind). I think allowing nonce gaps fully right now can introduce other issues (haven't thought it through) but perhaps we can allow gaps in the mempool only. Unless I'm missing something, the only issue with this is potential spamming (an attacker could fill your mempool with transactions that can't make it into blocks, because there's a gap) - and for a temp solution at this stage I'm not worried about that.

@dshulyak @countvonzero would love to hear your thoughts. If you agree and need my help with how to specifically implement this, lmk, otherwise just make me a reviewer.

**Comment by countvonzero** [comment]
> Did we make any changes to behavior in that region recently?

the logic that handle missing TXs from database has always been panic. that itself should be fixed. we should just let the node stay stuck instead of crashing.

wrt data availability, i think we should definitely make it mandatory. apart from that, we can also do
- increase the low level fetching retries per request (MaxRetriesForRequest) from 100 to higher number, hoping that one of the peers we connect to will receive the data within that time.
- try connecting to better peers. this of course involves more change, but i think we eventually have to have this mechanism anyway to improve sync speed.

@dshulyak i think this context switch is more involved than i want to take on now with the UCB impl so close to finishing.
but if you are not able to do it, plz let me know and i'll prepare a fix.

**Comment by dshulyak** [comment]
> I wonder how this issue never popped up until now

blocks that caused a crash had a substantial number of tx's (100, is it a limit?), in the previous networks we didn't have so many. usually, there were other problems.

>  suspect it's related to libp2p, since it's very similar to the block dependency problem we had right after switching to it.

i also thought about this. one way libp2p integration may have impacted this is because with libp2p we are verifying messages using multiple workers, previously all of them were verified in the same goroutine.

we definitely want to use non-blocking verification for ballots (because they may download stuff during validation and it takes time), atx's as they use cpu to verify them. but we have a way to verify transactions using single worker, but i don't know if it will work long term and for higher tx throughput.

but what i described is related only to gossiping, in direct messaging we may request transactions from multiple peers and each of them is processed concurrently. so if we receive tx with higher nonce sooner than the transactions with lower nonce the same problem will occur. this is very likely to cause this issue because we are guaranteed to send requests to different peers if number of requested hashes is large enough.

> Fixing the issue of dropping skipped transactions is harder and also temporary (as I said, we have a long term fix in mind). I think allowing nonce gaps fully right now can introduce other issues (haven't thought it through) but perhaps we can allow gaps in the mempool only.
 
i think it will be sufficient to fix this issue with two changes:
1. nodes should not be crashing if tx is missing (obviously), but they also should not be voting for the block if they don't have all transactions. otherwise, we don't know if the transaction is sufficiently propagated 
2. if the node is missing transactions when it needs to apply block - request transactions from peers and wait until all of them are downloaded, sort them by origin || nonce and push them to the mempool in order

optional:
3. max nonce gap for mempool will allow to receive some transactions out of order, but it is more of an optimization. if some nodes received them in order and included them into the block - then everybody else should be able to download them if sync is adjusted in a way that i described earlier  

> increase the low level fetching retries per request (MaxRetriesForRequest) from 100 to higher number, hoping that one of the peers we connect to will receive the data within that time.

not sure if this is necessary, sync already should be retrying indefinitely and we should fall back to it if hare failed to apply transactions to the state

@countvonzero i don't mind doing it, please check out if changes 1 and 2 may have any interaction with UCB

**Comment by dshulyak** [comment]
Actually, we don't even validate nonce when transaction is synced so 2nd change is unnecessary.

**Comment by countvonzero** [comment]
thanks @dshulyak 

> 1. nodes should not be crashing if tx is missing (obviously), but they also should not be voting for the block if they don't have all transactions. otherwise, we don't know if the transaction is sufficiently propagated

there are two stages:
- if a node fails to fetch TXs in a proposal, we should NOT save it to DB and, as a result, not put it forward in hare consensus.
- at the end of the hare consensus, if we cannot get TXs from all the proposals in the hare output, hare should fail for that layer and rely on sync later

> 2. if the node is missing transactions when it needs to apply block - request transactions from peers and wait until all of them are downloaded, sort them by origin || nonce and push them to the mempool in order

in UCB this should not happen. we only generate a block when all the TXs are available.

> push them to the mempool in order

prolly best to put this logic in tx pool instead of mesh.go

**Comment by countvonzero** [comment]
@dshulyak 
to be clear, we should first make sure data availability is guranteed.
https://github.com/spacemeshos/go-spacemesh/blob/develop/layerfetcher/layers.go#L622
we should make sure all hashes are fetched before validating a proposal/ballot/block

**Comment by dshulyak** [comment]
> to be clear, we should first make sure data availability is guranteed.
https://github.com/spacemeshos/go-spacemesh/blob/develop/layerfetcher/layers.go#L622
we should make sure all hashes are fetched before validating a proposal/ballot/block

yes, this is what i meant that we should not vote for block (proposal in UCB) if node can't download transactions

**Comment by noamnelke** [comment]
We used to have a mechanism in the old p2p module that marks a message as "seen" the first time it's received, to prevent double handling of gossip messages. How does this work with libp2p? If a message was received and rejected (e.g. due to gap in the nonce) what's the behavior the next time we receive it? Does sync bypass this mechanism?

If this behavior still exists and sync also ignores messages with hashes that were previously rejected, then we can retry and fail indefinitely.

---

> nodes should not be crashing if tx is missing (obviously), but they also should not be voting for the block if they don't have all transactions. otherwise, we don't know if the transaction is sufficiently propagated

That's true, but should be handled in the new TX selection, no need to implement it now. You've made me realize that I haven't spec'd the proposal handling, even though this was discussed with research - I'll add an issue for it.

---

So to reiterate: if what I wrote above still works this way, allowing gaps in the mempool may be the quickest fix, although making sync fetch even previously rejected messages is a must before genesis.

**Comment by dshulyak** [comment]
> If a message was received and rejected (e.g. due to gap in the nonce) what's the behavior the next time we receive it? Does sync bypass this mechanism?

yes, sync bypasses this mechanism.

> That's true, but should be handled in the new TX selection, no need to implement it now

i think this fix is not optional, allowing gaps only "improves" but doesn't fix completely.
