### ISSUE TITLE
Fix optimistic filtering feature

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/go-spacemesh#3384]
## Description
On the devnet 224, many smeshers got their node stuck on layer 23383.
After examining logs, @countvonzero points out the problem is in the new optimistic filtering feature.
I don't know any details, so it will be perfect if Kimmy can provide some details here 🙏 

There is [a part of the go-spacemesh log file](https://github.com/spacemeshos/go-spacemesh/files/9213662/stuck-logs.txt.zip) where Node syncs up to 23383 and gets an error the first time (check out line 458).
After the error occurred we can see that the Node retries to sync forever, but always fails due to the same reason.

## Steps to reproduce
1. Run the Node against the network 224
2. Try to sync to the top layer

## Actual Behavior
There is a big chance (I'm not sure that it is 100%) that your node will get stuck on layer 23383.

## Expected Behavior
Node syncs without any issues.

## Environment
 - OS: Any (caught on macOS and Windows)
 - Node Version: 0.2.17-beta.0

**Comment by countvonzero** [comment]
i'd name this bug to "bypass optimistic filtering". the bug won't be fixed in the latest release binary for devnet, but it can be bypassed by setting config.

however, for go-spacemesh, a large portion of the config is baked into the binary with the flag --preset. we will need to 
- set this flag to null in confg.json 
- explicitly set all the params included in the preset config file in confg.json
- set `optimistic-filtering-threshold` to 100

**Comment by brusherru** [comment]
@countvonzero I filed another one issue for that just now: #3385 

So, I think that:
- this issue is about fixing the bug in the code for the next releases
- #3385 is about a quick fix for the current devnet, without making any changes in go-spacemesh

Is it right?

**Comment by countvonzero** [comment]
it's already fixed per issue #3346, PR #3375

**Comment by brusherru** [comment]
Oh, awesome!
Then I'm closing this issue :)
