### ISSUE TITLE
ATX: allow variable units over time for the same smesher ID

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3773]
### context
- for smeshing whales, disk failures is a given. 
- in the interest of minimizing the amount of ATXs in the network, we don't want to incentivize whales to split identities into smaller disks.
- whales need to read all of its PoST data within a relative narrow window (8-12hrs? after previous PoET phase ends and before next PoET phase begins)
 
combined all above considerations, we want to allow ATXs from the same smesher ID to have fluctuating num units over time. 

### considerations
- how to deal with actual disk unit increase/decrease?

**Comment by noamnelke** [comment]
Worth noting that we can only easily support decreasing entire space units. We could support increasing the number of units, too, but that would require re-validating the POPS-VRF index (with a higher difficulty) and deciding when exactly the new value takes effect. Not impossible, but baby steps.

If not an entire space unit is lost, the smesher has a choice to either discount the entire unit or to recreate the missing part. If the lost part is small enough, it's possible that nothing needs to be done at all and a valid proof can be constructed anyway.

# Rough spec
## Validate that `NumUnits` only decreases
`NumUnits` is already declared in every ATX.

I was sure we validate that `prevATX.NumUnits == atx.NumUnits`, but apparently we don't 😅.

Instead, in `handler->SyntacticallyValidateAtx()`, we should validate that `prevATX.NumUnits >= atx.NumUnits`.

## Use the lower `NumUnits` of this ATX and the previous

When syntactically validating the ATX (`handler->SyntacticallyValidateAtx()`) we fetch the previous ATX. At that point, we should store in the `VerifiedActivationTx` a new field `EffectiveNumUnits := min(prevATX.NumUnits, atx.NumUnits)`.

Then we should change this:
```go
func (vatx *VerifiedActivationTx) GetWeight() uint64 {
	return getWeight(uint64(vatx.NumUnits), vatx.tickCount)
}
```
To use `EffectiveNumUnits` instead of `NumUnits`.

**Comment by lrettig** [comment]
@noamnelke could you explain this part?

> If the lost part is small enough, it's possible that nothing needs to be done at all and a valid proof can be constructed anyway.

**Comment by lrettig** [comment]
Another potential use case: allow a miner to start smeshing sooner, with less initialized space, while they continue to initialize more space in the background. They'd want to scale up their committed space each epoch until they reach their target.

**Comment by noamnelke** [comment]
> @noamnelke could you explain this part?
> 
> > If the lost part is small enough, it's possible that nothing needs to be done at all and a valid proof can be constructed anyway.

Sure.

If there's a bad sector on a disk and just a few percent of labels are lost, we could just skip those labels when trying to construct a PoST proof. The process is statistical (we're looking for a predefined number of labels that, when hashed with a challenge, result in a number below some threshold), so we could succeed in constructing a proof even without the missing labels. If we don't, there's a process in place to deal with it.

Having said that, this might not work out-of-the-box. **We need to ensure that the PoST implementation, when failing to read from disk, skips the labels that it failed to read (logging the event), rather than fail outright.** ⚠️ @countvonzero 

Ultimately, when we find out that we're missing labels (failing to read them when trying to construct a proof) we should start to reconstruct the missing part in the background so this is fixed by the next epoch. This is a little trickier to do (need to check for free disk space, we may want to have a config that decides if this is done automatically or requires user involvement, etc.), so we can postpone this PoST fix to post-genesis (try to say this out loud).

**Comment by noamnelke** [comment]
# Supporting Space Increases
As mentioned above, it's slightly harder to support increasing allocated space than decreasing. However, it would be very nice if the initial implementation supported validating ATXs that do this, even if we don't implement the actual increasing space part. This will allow introducing what @lrettig suggested above (start smeshing quickly and increase storage gradually) without needing a fork.

I believe supporting this is easy enough, but I leave it to @pigmej @lrettig and @countvonzero to decide if we can squeeze it in before genesis or not.

## Spec
### Allow `NumUnits` to both increase and decrease
When considering a smesher's weight for the target epoch, use the lesser of the last two reported (and validated) `NumUnits`. This means that a we assume that an increase happens right before constructing a NIPoST and a decrease happens right after constructing the previous NIPoST. While in reality it could be anywhere in between we must assume the worst because we have no better proof.

We may need to cache the `EffectiveNumUnits` with the ATX, so that we won't need to repeatedly fetch the previous ATX. If we already cache the resolved weight (that factors in the PoET ticks as well) then this is probably not needed.

#### Examples
```
atx.PrevATX.NumUnits = 7
atx.NumUnits = 5
EffectiveNumUnits = 5
```
```
atx.PrevATX.NumUnits = 3
atx.NumUnits = 4
EffectiveNumUnits = 3
```

### Allow updating `VRFNonce`
The ATX has a `VRFNonce` field that is normally only populated in a smesher's first ever ATX (similar to `InitialPost`). In many cases, increasing the allocated storage will result in needing to update this value. This will not always be the case when increasing storage, since the previous value may satisfy the requirements of the increased storage as well.

I don't see that we're currently using the `VRFNonce` value anywhere, other than validation in a smesher's first ATX. I'm guessing this is WIP in some PR or something, so I'm tagging @fasmat so that he's aware of this possible change and update this thread on what needs to be updated to support changing this value when it's actually used.

### Validate `VRFNonce`
When `NumUnits` is increased, wether or not a new value of `VRFNonce` was declared - we must re-run `ValidateVRFNonce()`. If a new value of `VRFNonce` was declared, the need is obvious, but even if no new value was declared, the new, higher, value of `NumUnits` may cause the validation to fail.

If validation fails, this should be handled like any other syntactically invalid ATX being received. If it's signed by the smesher, but fails other validation checks, the smesher should be blacklisted. If this is not currently how we handle things, we can keep doing what we're doing in other cases, for now.

**Comment by fasmat** [comment]
I will close this in favour of https://github.com/spacemeshos/pm/issues/209. PoST size can already be changed over time (at least on Protocol level) and the other issue tracks the details necessary to make it possible on an implementation level.
