### ISSUE TITLE
hare: reduce data volume for genesis

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3916]
## description

it is decided that we will not implement https://community.spacemesh.io/t/hare-data-volume-optimization/330 for genesis.
instead, we do the following to alleviate
- reduce committee size from 800 -> 400 (decrease security)
- sanity check on hare message based on type (so nodes don't gossip spam messages that bloat up hare messages)

## fields usage map

In the current codebase we reuse the same data structure (`InnerMessage`) for all messages in Hare. Hence, sanity check must be applied so to ensure that fields not used for given message type are really left empty by the creator of the message. In the table below the usage of fields is specified:

![msg-types-map](https://user-images.githubusercontent.com/4654168/210258983-6bdff097-e929-4147-ac37-e41bf3e214d2.PNG)

**Comment by countvonzero** [comment]
@selfdual-brain please fill in the detailed spec. thank you

**Comment by dshulyak** [comment]
i will cross post from slack, if 1gb per iteration is correct this change will reduce bandwidth from ~6gb down to 1.5gb per iteration. doesn't change much in my opinion

> just a note about hare bandwidth
Wojtek estimation of 1gb per iteration is probably doesn't include gossip protocol amplification, which is configured and somewhere between x6-12
it can be tuned down to no amplification, but at the cost of higher latency, i don't know if it is safe to do for hare

**Comment by selfdual-brain** [comment]
I agree that we need more aggressive reduction of committee size. Instead 800->400 reduction, I would suggest measuring data volume on 3 test networks with committee size set to 200:
- one network with ~500 nodes
- one network with ~`1000 nodes
- one network with ~`2000 nodes

If the data volume upload+download measured (for a single node) is:
- within 100 MB per layer
- does not look like increasing with the network size
... we should accept this as "not perfect but acceptable" for Genesis

Otherwise, there are still 2 rescue options on the table:
- Option 1: Implement commit certificate with hashed list of messages; Although we know this variant of the protocol is not provably safe, it would still be safer than decreasing committee size below 200 (but I would like to hear an opinion from @tal-m on this option) 
- Option 2: Drop Hare 1.0 whatsoever and go for a full Hare 2.0 implementation (this of course would introduce additional delay in our roadmap)

The calculation of Hare date volume I made a month ago was based on several idealizations/simplifications and may not properly reflect the actual data volume. I primarily made these calculations to build our understanding around root causes of the surprisingly large data volumes observed, and also to use this a a point-of-reference for calculating idealized data volume for other theoretical variants of the protocol. In my calculations I assume completely idealized gossip protocol ("magic-gossip").

**Comment by countvonzero** [comment]
> I agree that we need more aggressive reduction of committee size. Instead 800->400 reduction, I would suggest measuring data volume on 3 test networks with committee size set to 200:
one network with ~500 nodes
one network with ~1000 nodes
one network with ~2000 nodes

is this something you can calculate with the simulator?
it seems doable to calculate data volume per iteration (without gossip), and multiply the gossip factor (x6-12).

**Comment by selfdual-brain** [comment]
I do not know enough about the internal implementation of libp2p to properly calculate the gossip overhead. In particular I do not know how this overhead scales with network size.

From the pure Hare point of view, once the network size exceeds the committee size, the data volume exchanged during Hare should not depend on the network size.

In the experiment I suggested above, I generally expect to observe approximately the same data volume for all 3 network sizes. But this "should" be double-checked.

**Comment by dshulyak** [comment]
this is a part of hare3
