### ISSUE TITLE
activation: StartSmeshing should not fail silently

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4292]
related codebase: https://github.com/spacemeshos/go-spacemesh/blob/develop/activation/activation.go#L193-L195

it can fail due to validation, but operator won't even know that smeshing didn't start, which is not that fun..
we also may consider using values specified in post_metadata.json , instead of defaults in the config, if such file already exists

**Comment by pigmej** [comment]
Reading the values from `post_metadata.json` is a must IMHO.

**Comment by piersy** [comment]
Hi @dshulyak & @pigmej

I've had a look into the code and the situation is that `StartSmeshing` starts a goroutine that begins the initialization process. the goroutine returns the result when stop smeshing is called, so you can get the error that occurred at init start but you just have to call stop smeshing.

It would be nice to separate all the setup/validation of initialization from the actual work, so that we could setup/validate everything and then if that succeeds start a goroutine to do the actual work. This way we would be able to directly return an error from the start smeshing endpoint. That looks like it could be quite a lot of changes though since the setup/validate is spread across 3 functions in 2 objects. Also we can't guarantee that something wont break as soon as we call the work oracle. So as much as we try with this approach, it seems like there's still the possibility of a silent failure.

An alternative would be to change the api to stream results back to the caller. In this way as soon as something goes wrong the caller can be notified, but we could also extend this to provide a progress report on initialization which could be nice for users.

And I'm thinking of a third hacky way which could be to wait some time after calling start, and then check the error channel for any errors and if so return that from the start smeshing API call, and otherwise continue.

I'd like to hear your thoughts/preferences for these options?

**Comment by piersy** [comment]
In discussions with @pigmej & @dshulyak it seems that crashing is an acceptable option here. So what we can do for now is validate what we can easily up front and crash on any subsequent failure.
