### ISSUE TITLE
don't store activeset together with ballot object

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/go-spacemesh#4984]
activeset is the main reason why database grows at such rate. 

- drop activeset from ballots blob. don't send it over sync either. sync will request activeset with another rpc
- across application request activeset using activesets.Get function, without an sql join to ballot table

**Comment by dshulyak** [comment]
i looked into this briefly. the solution i think is to:

- run migration that decodes ballots, saves unique active sets, and updates ballot without active set but with a reference to activesets table
- vacuum && checkpoint
- all new ballots store active set only in activeset table
- allow to download active set for all blocks, not only latest (this restriction is harmful https://github.com/spacemeshos/go-spacemesh/blob/develop/proposals/handler.go#L469-L471)
- for code that needs activeset, get it by join on activeset table

**Comment by countvonzero** [comment]
> for code that needs activeset, get it by join on activeset table

this requires adding activesetHash to ballots table.

> - run migration that decodes ballots, saves unique active sets, and updates ballot without active set but with a reference to activesets table
> - vacuum && checkpoint

i find it risky to do all these in one step/software upgrade, especially this is not a down-gradable release.

assuming the network has 1.1.5 now.

what do you think if we first release 
1.1.6 with
- a migration that 
  - delete propsals/certs/proposal txs
  - goes through ballots table and extract active set to the activesets table
- regular background pruning
- vacuum && checkpoint (for the proposal deleted)
- all new ballots store active set only in activeset table
- allow to download active set for all ballots 
- make sure no codepath access `ballot.ActiveSet` directly. 

at this point, there is no data loss and app only access `ballot.EpochData.ActiveSetHash`. 1.1.5 and 1.1.6 are compatible

then we release 1.2.0 with
- a migration that prune all the active sets from ballots
- vacuum && checkpoint

1.2.0  is compatible with 1.1.6 but not with 1.1.5, and is down-gradable. and we 
- get higher confidence that the data loss is ok because 1.1.6 is working
- provide a bigger incentive to upgrade 1.2.0 due to the much reduced state size.

**Comment by dshulyak** [comment]
> this requires adding activesetHash to ballots table

this is one of the options. the other one is to fetch activeset with another query. would work as well

we can do it the way you suggested. the downside that 8GB will be allocated for 1-2 additional weeks. not a big deal
