### ISSUE TITLE
Addressing Concerns and Proposing Solutions for Spacemesh Network Health and Decentralization

### ISSUE THREAD

**Issue by bugxzhu** [spacemeshos/go-spacemesh#5115]
Dear Spacemesh Team,

I would like to share some concerns and suggestions regarding the Spacemesh network. First and foremost, I want to express my support and interest in the Spacemesh project. Your work and vision in the blockchain space have garnered widespread attention. However, there are some issues of concern at present, particularly related to pool control and the reward mechanism.

In the current Spacemesh network, it appears that the H9 pool has gained control of a significant portion of the hashing power. This raises concerns as a very small number of nodes within the H9 pool seem to be able to control a large portion of the network's hashing power, posing a threat to the project's health and decentralization. This situation is not only unfriendly to newcomers but also poses centralization risks.

Another issue pertains to the reward mechanism. Currently, miners in the H9 pool can stop their nodes immediately after completing a Post and still remain eligible for rewards. In contrast, solo miners are expected to keep their nodes online continuously, which is considered unfair to some extent. This could lead to more people joining the H9 pool, which goes against the original decentralized vision of the Spacemesh project.

Lastly, concerns related to miners being able to continue receiving rewards after shutting down their nodes may negatively impact the price stability of the Spacemesh token. Because miners can easily shut down their nodes, this results in a very low cost for earning rewards, potentially causing instability in the supply of rewards and affecting the market price of the token.

Therefore, I strongly urge the Spacemesh team to consider introducing mechanisms to combat pool dominance and ensure the network's health and decentralization are maintained. This may involve limiting the hashing power share of individual pools or implementing other technical measures to mitigate centralization risks. Additionally, a review of the reward mechanism to ensure fair miner participation consistent with the project's vision is recommended.

Once again, thank you for your work and contributions to the blockchain space. I look forward to seeing the continued success of the Spacemesh project while preserving its decentralized and community-friendly characteristics.

Best regards

**Comment by noamnelke** [comment]
Dear @bugxzhu,

Thanks for your deep interest in the Spacemesh project and for raising this valid concern directly with us.

As you must imagine, we're aware of what H9 is doing and it's impact on smeshers and the security and decentralization of the network. Unfortunately, preventing this behavior effectively in a permissionless system is not as easy at it may appear. Since we don't know of a way to outright block node delegation, we're taking steps to provide users with an alternative that's safe for them and the network, if their particular situation requires running a node separately from where their PoST data is stored and processed (similar to what H9 offers). Unlike the H9 solution, running your own trusted node (on a separate machine) will not require sharing revenue or your private key with anyone. We've talked to users who chose to use the H9 client and many of them, specifically larger smeshers with significant weight, mainly use the alternative client because the cost and complexity it saves them is greater than the fee they pay H9. Given the solution we're currently building they would not choose to depend on the pool.

I invite you to track our implementation progress here: https://github.com/spacemeshos/pm/issues/259

The main cost of smeshing was always supposed to be the cost of storage. While H9 users can save some complexity due to not running their node 24/7, they must still allocate storage like any other smesher. As explained above, soon anyone with more than one node will be able to [run a single node instance](https://github.com/spacemeshos/pm/issues/261) for all of their "PoST-only nodes" and anyone who can't run their computer 24/7 will be able to run a node in the cloud or on a Raspberry Pi, separately from their storage--leveling the playing field.

It's important to remember that there are no "magic solutions". Existing H9 users are not likely to transition to the safer solution instantly, and H9 might also respond with other offerings. This is an ongoing process. For now rest assured that we're not taking this issue lightly and that the safety and decentralization of the network remains our top priority.

**Comment by bugxzhu** [comment]
> Dear @bugxzhu,
> 
> Thanks for your deep interest in the Spacemesh project and for raising this valid concern directly with us.
> 
> As you must imagine, we're aware of what H9 is doing and it's impact on smeshers and the security and decentralization of the network. Unfortunately, preventing this behavior effectively in a permissionless system is not as easy at it may appear. Since we don't know of a way to outright block node delegation, we're taking steps to provide users with an alternative that's safe for them and the network, if their particular situation requires running a node separately from where their PoST data is stored and processed (similar to what H9 offers). Unlike the H9 solution, running your own trusted node (on a separate machine) will not require sharing revenue or your private key with anyone. We've talked to users who chose to use the H9 client and many of them, specifically larger smeshers with significant weight, mainly use the alternative client because the cost and complexity it saves them is greater than the fee they pay H9. Given the solution we're currently building they would not choose to depend on the pool.
> 
> I invite you to track our implementation progress here: [spacemeshos/pm#259](https://github.com/spacemeshos/pm/issues/259)
> 
> The main cost of smeshing was always supposed to be the cost of storage. While H9 users can save some complexity due to not running their node 24/7, they must still allocate storage like any other smesher. As explained above, soon anyone with more than one node will be able to [run a single node instance](https://github.com/spacemeshos/pm/issues/261) for all of their "PoST-only nodes" and anyone who can't run their computer 24/7 will be able to run a node in the cloud or on a Raspberry Pi, separately from their storage--leveling the playing field.
> 
> It's important to remember that there are no "magic solutions". Existing H9 users are not likely to transition to the safer solution instantly, and H9 might also respond with other offerings. This is an ongoing process. For now rest assured that we're not taking this issue lightly and that the safety and decentralization of the network remains our top priority.

thanks.
I very much look forward to the continued improvement of spacememsh.
