### ISSUE TITLE
node sync is stopped hours

### ISSUE THREAD

**Issue by centny** [spacemeshos/go-spacemesh#5542]
## Description
node sync is stopped hours

## Environment
Please complete the following information:
 - OS:  ubuntu22.04/docker
 - NODE: v1.3.5-hotfix2

## Additional Resources 
[s3005.log](https://github.com/spacemeshos/go-spacemesh/files/14166390/s3005.log)

**Comment by imaiops** [comment]
+1

**Comment by isReset728** [comment]
+1 
same question
{"status":{"connectedPeers":"19","isSynced":false,"syncedLayer":{"number":59484},"topLayer":{"number":59505},"verifiedLayer":{"number":59483}}}

**Comment by centny** [comment]
never synced, must delete node data and copy from another ndoe.

[m3101.log](https://github.com/spacemeshos/go-spacemesh/files/14195831/m3101.log)

**Comment by pigmej** [comment]
Did the situation improve recently?

@imaiops, in your case, the node seems to be busy with ATX verification or similar. As you can see, the synced vs verified are different, so most likely, it was moving.

Please make sure that you're running on the latest software (1.3.9 at the moment of writing)

In any case please keep the nodes on, they will eventually sync. Network was heavily overloaded because of the number of ATX

**Comment by dshulyak** [comment]
it will be more visible in v1.4 and atx sync in general should work
