### ISSUE TITLE
Pre-round messages equivocation

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#564]
How equivocation is handled for pre-round messages?

**Comment by gavraz** [comment]
* We shouldn't ignore extra pre-round messages 
* We can't pick the lower one because it affects the status messages that we have already sent (provable values may become non-provable and vice versa)
* Should consider union of the messages
* Waiting for input from Julian

**Comment by jlspacemesh-zz** [comment]
The issue seems to me to be more of an implementation related issue, because on paper, one would always consider the entire view of the network.
So, here is what we need to do, concretely:

- If you are verifying the correctness of a SVP in any step, use your entire view of the network state, i.e., don't disregard messages from sender that obviously cheated in your view.

- If you are forming an SVP at any step, it is fine to disregard such messages and just use messages that appear to you as "honest values".

**Comment by zalmen** [comment]
@jlspacemesh , what do you mean by "use your entire view of the network state". Does it mean that if a participant received two PreRound messages from the same sender it should use the union of the messages when validating an SVP?

**Comment by jlspacemesh-zz** [comment]
Yes, but not necessarily when forming the SVP, which was, I think, the main point of confusion...
