### ISSUE TITLE
Serve API per each NodeID configured / known poets

### ISSUE THREAD

**Issue by ConvallariaMaj** [spacemeshos/go-spacemesh#6174]
per each POST identity configured / known poets (with some warning if they are missmatched)

**Comment by pigmej** [comment]
So, we need an endpoint that returns PER IDENTITY:
* which poets did It register into successfully (200 ok from the poet)
* which poets it failed to register into (i.e., 429 for the registrations and ran out of time before the round started, etc.)
* which poets it has no idea about (i.e., added to the config just now but not found in the DB)

That will allow users to understand what's the situation with the poets

**Comment by fasmat** [comment]
That means failed registrations also need to be persisted into the local DB in a way that it makes clear which registrations are valid and which failed. This can probably be easiest achieved by leaving the `RoundID` field empty and setting the `RoundEnd` time to what it would have been according to the configuration of the node. When fetching the proofs from PoETs an additional check is needed such that when no `RoundID` is available it doesn't actually try to query the PoET for the proof.

When returning the current state of the identities if there are any registrations in the DB it should list the registrations with the following information (gathered from DB and config):

- URL of the PoET the challenge was submitted to
- End of the PoET round (when the node will fetch the proof)
- Status
   - Registered: PoET is in config and registration was successful
   - Failed registration: PoET is in config and registration failed
   - Residual registration: PoET was registered to, but is not in config <- could indicate needed intervention by user
   - No registration: PoET is in config but was never registered to <- user added PoET to configuration after current round already started

This info should in my opinion only be returned if the identity is currently waiting to fetch proofs from PoET, otherwise the current state of the identity should be returned instead: 

- waiting to submit challenge to PoET
- creating PoST proof / publishing ATX
- creating initial PoST
- waiting for state `ATX Synced` (which is a pre-requisite for the other states)
