### ISSUE TITLE
Finish discovery "Ping" feature

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/go-spacemesh#718]
# Overview / Motivation
*TODO*: choose a better name
we want to be able to ensure nodes are listening where they claim to. nodes advertise themselves with a `ping` message with their IPs and ports, we should validate they're listening with another ping message to this address.

# The Task

Implement a mechanism that remembers which peers we pinged lately (and got ponged back), condition sending `Addresses` messages to peers only after we pinged them and got ponged. this serves to protect other peers from reflected denial of service where an attacker could spoof source address in order to make honest peers sending many large `Addresses` messages to a victim.

# Implementation Notes

should be implemented around the `verifyPinger` method.

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

**Comment by lrettig** [comment]
Testing my own understanding of the status quo and the requested change--could you please let me know if this is all accurate? Thanks!

# The protocol today

A. As it stands now, as part of the discovery bootstrap process, a node will first send a `PING` message (containing its nodeinfo, i.e., ID, IP, and port) to each of its current peers. Then, for each peer that sends a valid "ping response" (also containing the peer's nodeinfo), the node will follow up with a `GET_ADDRESSES` message. When it receive a response, it  performs some basic validation (making sure that it's not an empty set, or too large), then adds new results to its address book.

B. Upon receipt of the `PING` message, each peer only verifies that the nodeinfo contained in the message is valid (`verifyPinger()`), adds the address to its own routing table, then responds to the message with its own peerinfo.

C. Upon receipt of the `GET_ADDRESSES` message, each peer performs no additional verification and immediately responds with a list of its peers (not including the sender of the message).

# Desired change

A node should only respond to a `GET_ADDRESSES` message if it's recently pinged the message sender at the advertised IP and port, and gotten a valid response back. If it hasn't thus verified the pinger yet (or not recently enough), it must complete this roundtrip verification before responding to the `GET_ADDRESSES` message.

This verification step should happen when it receives the `PING` message, i.e., as part of `verifyPinger()` (such that, when it receives the `GET_ADDRESSES` message, it will have just verified the peer and won't need to perform the verification again). It should respond to the `PING` message _before_ sending its own `PING` to the same peer so that that peer doesn't try to `PING` it, preventing an infinite loop of pings.

**Comment by y0sher** [comment]
Yes, this is exactly the desired change!
the only thing is that in the first paragraph (the protocol today) you say `to each of its current peers`, we don't hold a set of `peers` in the discovery protocol, as this protocol is based on UDP messaging. you can send a message to any peer info record your holding. they are chosen randomly from the routing table on a bootstrap/refresh. so no notion of the current peers, but just pick a random peer from all the info (routing table/ addrbook) we have.
