### ISSUE TITLE
eligibility for Hare protocol

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/go-spacemesh#816]

**Comment by barakshani** [comment]
For Hare committee eligibility, we rely on the total number of active units *in consensus*. This means we can't just use all syntactically valid ATXs received in the previous epoch, since honest parties might disagree about them.  Instead, we define a "confidence interval", $k$, such that w.h.p. all honest parties agree on the contextual validity of all blocks at least $k$ layers in the past. Think of $k$ as 100 at this point (this should be about the same as the tortoise window size).

We say the "consensus view" of layer $j$ is the union of the views of all contextually valid blocks in layer $j$. 

Denote \eptime the number of layers in an epoch.

Activation and Difficulty:  Let $ep=\lfloor (i-k)/\eptime \rfloor $ be the greatest epoch index smaller than i-k (i.e., layer i-k is in epoch ep). 

We consider an id *active* at layer $i$ if, in the consensus view of layer $ep\cdot \eptime + 1$, it has an active ATX (i.e., there's a syntactically valid ATX belonging to the epoch before that of layer $i-k$). Note that if $i$ is less than $k$ layers after the epoch boundary, this means we count only activations *two* epochs before $i$.  Also, since history is generally irreversible, in the optimized setting we can assume that once we are $k$ layers past the epoch boundary the active set won't change for the rest of the epoch.

The difficulty $d$ for layer $i$ is the number of active ids at layer $i$.

**Comment by barakshani** [comment]
Related issue:
https://github.com/spacemeshos/go-spacemesh/issues/1054
