### ISSUE TITLE
Reasearch potential POST GPU implementation

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/go-spacemesh#966]

**Comment by avive** [comment]
I can take over this task if needed. I've started to hack OpenCL sha256() already. The issue is the probability of us using shaXXX() for mainent - we need to get a clear direction from the research team regarding the POST hash function we want to use. This is an important issue. The informal requirements are, as far as I understand them is  that using a GPU should be at least x10 cost-effective (energy spent per same proof) than CPI, and a known ASIC not more than x10 cost effective than GPU. Natural candidates are CuckohashXXX / progPoWork. @barakshani @iddo333 - clarify from research is needed here. Finding the best hash function to implement is a hard problem. Once the algo is found - putting together a GPU implementation that works both in NVIDIA and AMG GPUs should be straight-forward.

**Comment by moshababo** [comment]
Project was implemented here: https://github.com/spacemeshos/gpu-post
